packages/core/src/extensions/Blocks/nodes/Block.ts
This PR fixes a bug introduced in the previous commit which removed the `data-id` attribute from blocks, which most notably causes issues with the drag handle.
=> Re-add data-id attribute to blocks

packages/core/src/extensions/Blocks/BlockAttributes.ts, packages/core/src/extensions/Blocks/PreviousBlockTypePlugin.ts, packages/core/src/extensions/Blocks/nodes/Block.module.css, packages/core/src/extensions/Blocks/nodes/Block.ts
BlockNote keeps track of what node type a block currently is (paragraph, heading, list, etc), as well as what type it was previously. This is done using custom HTML attributes using kebab-case (e.g. `data-heading-type` and `prev-data-heading-type`) to animate when the block type changes. Previously, these attributes used improper naming conventions (actually `data-headingType` and `prev-data-headingType`). PR #46 improved the naming scheme for the current block type attribute but not the previous type, which broke animations. This PR changes the previous block type attribute to also comply with kebab-case naming conventions, and subsequently fixes the animations.
=> Block animation fix

packages/core/src/extensions/Blocks/nodes/Block.ts, packages/core/src/extensions/UniqueID/UniqueID.ts, tests/end-to-end/draghandle/draghandle.test.ts, tests/utils/draghandle.ts
This PR moves code for rendering the `id` attribute of blocks to the same place as all other block-specific attributes, while it was previously done separately as part of the UniqueId extension. This should also be a more robust fix for ensuring the `id` node attribute/`data-id` HTML attribute does not get accidentally removed from blocks in the future.
=> Move block `id` attribute rendering code

packages/core/src/extensions/Blocks/OrderedListPlugin.ts
Now order list counter correctly calculates per `blockgroup` layer.
=> fix order list counter

packages/core/src/editor.module.css
Fixes issue reported on Discord:
=> fix draghandle bug

examples/editor/src/App.tsx, examples/vanilla/src/main.tsx, packages/core/src/BlockNoteEditor.test.ts, packages/core/src/BlockNoteEditor.ts, packages/core/src/api/nodeConversions/nodeConversions.ts, packages/core/src/extensions/Blocks/api/blockTypes.ts, packages/core/test/__snapshots__/blockManipulation.test.ts.snap, packages/core/test/__snapshots__/formatConversions.test.ts.snap, packages/core/test/__snapshots__/nodeConversions.test.ts.snap, packages/core/test/blockManipulation.test.ts, packages/core/test/formatConversions.test.ts, packages/core/test/nodeConversions.test.ts, packages/react/src/BlockNoteView.tsx, packages/react/src/hooks/useBlockNote.ts
This PR:
- removes the difference between BlockNoteEditor and EditorAPI. API methods are directly accessible on blocknoteeditor.
- renames tiptapEditor to _tiptapEditor to clarify it's only for internal use
- We only allow our own `BlockNoteEditorOptions` instead of having it extend from Tiptap's options. This way we can design + document our own API. (and if we want to at some point, we can remove TipTap later)
=> make api accessible via editor, hide tiptap initialization options

packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts
- add support for dragging / dropping next to the editor
- fixes drag previews for nested items
=> fix dragimage + allow dragging next to editor

examples/editor/package.json, lerna.json, package-lock.json, packages/react/package.json, packages/react/vite.config.ts, packages/website/docs/.vitepress/theme/components/Sandbox/Sandbox.vue, packages/website/package.json
The sandpack demos fail when Tippy components appear. The issue is that it doesn't correctly resolve the Tippy default import from `@tippyjs/react`
This is a regression from v0.3.0, which was built with an older version of Rollup. 
Old code shows `.default`, where new builds don't
=> fix umd build for sandpack

examples/editor/package.json, examples/vanilla/package.json, lerna.json, package-lock.json, packages/core/package.json, packages/core/src/extensions/Blocks/nodes/BlockContent/HeadingBlockContent/HeadingBlockContent.ts, packages/core/src/extensions/Blocks/nodes/BlockContent/ListItemBlockContent/BulletListItemBlockContent/BulletListItemBlockContent.ts, packages/core/src/extensions/Blocks/nodes/BlockContent/ListItemBlockContent/NumberedListItemBlockContent/NumberedListItemBlockContent.ts, packages/core/src/extensions/Blocks/nodes/BlockContent/ParagraphBlockContent/ParagraphBlockContent.ts, packages/react/package.json, packages/website/package.json
This seems to fix the HTML -> Node conversions. @matthewlipski Any reason why `node` was always set to `blockContainer`?
I'm not sure why this worked locally btw in the unit tests. But the published version now at least also works in codesandbox
=> Fix node html parse

packages/website/docs/docs/converting-blocks.md
This PR fixes a line in the docs that uses the old `editor.allBlocks` call instead of the updated `editor.topLevelBlocks`.
=> Minor docs fix

packages/core/src/BlockNoteEditor.ts, packages/website/docs/docs/editor.md
This PR adds the `initialContent` editor option which allows for loading content into the editor on creation.
=> Editor option for initial contents

packages/core/src/BlockNoteEditor.ts
The PR changes some parameters for block manipulating functions in `BlockNoteEditor` to use `BlockIdentifier`s as they should. Also fixes `forEachBlock` callback to return a boolean.
=> fix: parameters and foreachblock

packages/core/src/BlockNoteEditor.ts, packages/core/src/editor.module.css, packages/core/src/extensions/Blocks/nodes/Block.module.css, packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts, packages/website/docs/docs/editor.md
Fixes https://github.com/TypeCellOS/BlockNote/issues/144. With this change, users can prevent the "css reset" of block styles
Todo:
=> add defaultStyles option, reorganize styles

examples/editor/package.json, examples/vanilla/package.json, lerna.json, package-lock.json, packages/core/package.json, packages/core/src/editor.module.css, packages/react/package.json, packages/react/src/utils.ts, packages/website/package.json
Nextjs now doesn't cause bugs anymore, and no `dynamic` needed anymore either
Closes https://github.com/TypeCellOS/BlockNote/issues/146
=> fix nextjs bug

packages/react/src/FormattingToolbar/components/LinkToolbarButton.tsx, packages/react/src/HyperlinkToolbar/EditHyperlinkMenu/components/EditHyperlinkMenu.tsx
This PR fixes a bug which causes the link creation menu to disappear when clicked on.
=> Link creation menu fix

packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/HyperlinkToolbar/HyperlinkToolbarPlugin.ts, packages/core/src/shared/plugins/suggestion/SuggestionPlugin.ts
The menus and toolbars currently stay in place when the page is scrolled. This PR makes makes their positions update on scroll.
closes https://github.com/TypeCellOS/BlockNote/issues/165
=> fix: menu positioning when scrolling

packages/react/src/SlashMenu/components/SlashMenu.tsx
martine menu dropdown position style is set to "absolute". 
The tippy container's ( the parent of dropdown menu ) computed width and height are 0.
This makes popper overflow not work when change the type of last several blocks.
before fix, popper's overflow detection not work:
after fix, popper's default flip behavior work:
=> fix: slashmenu dropdown positioning on edge of page

packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts
Solves: https://github.com/TypeCellOS/BlockNote/issues/80
[Nodes eq method](https://github.com/ProseMirror/prosemirror-model/blob/95298fb02744e1a8f41eae50f8a6afde583a8817/src/node.js#L118) returns true if the two nodes are either the same instance or if their markup and content is the same. In this case the markup or content of the Nodes do not matter and the condition should only be true when the instance is not the same.
When dropping a selection of multiple blocks outside of the editor the selection type stays the same as it got set [here](https://github.com/TypeCellOS/BlockNote/blob/main/packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts#L217). If the selection gets dragged again and is of type `MultipleNodeSelection` we can be sure that the user drags multiple …
=> fix: dragging multiple blocks

packages/core/src/BlockNoteEditor.ts, packages/react/src/hooks/useBlockNote.ts, packages/website/docs/docs/editor.md, packages/website/docs/docs/formatting-toolbar.md, packages/website/docs/docs/side-menu.md
This PR fixes & improves the API for creating a custom Formatting Toolbar and Drag Handle Menu.
=> fix: Custom UI element API

packages/website/docs/.vitepress/theme/components/Examples/BlockNote/ReactBlockNote.module.css, packages/website/docs/.vitepress/theme/components/Hero/Hero.vue, packages/website/docs/.vitepress/theme/components/Home.vue
The editor demo on the home page had a bug where creating too many blocks would cause them to render beyond the y-boundary of the demo box. This PR fixes that and makes the demo box scrollable.
Closes #204
=> docs: fix overflow for website editor demo

packages/react/src/BlockSideMenu/components/DragHandleMenuItem.tsx
Filter out closeMenu from the props so React stops warning about it.
To generate the warning without this change, simply click on the drag handle menu with your dev console open.
=> fix: Address React Warning when clicking DragHandleMenuItem

packages/core/src/api/nodeConversions/__snapshots__/nodeConversions.test.ts.snap, packages/core/src/api/nodeConversions/nodeConversions.test.ts, packages/core/src/api/nodeConversions/nodeConversions.ts, packages/core/src/extensions/Blocks/api/inlineContentTypes.ts
When you press Shift+Tab in a block, it creates a new line in the same block which TIpTap/ProseMirror store as a `hardBreak` node. It turns out we completely forgot about these when doing inline content conversions, so this PR remedies that.
This also fixes the `Empty text nodes are not allowed` error that some people have been getting, mentioned in issues #184 and #216.
Closes #184
Closes #216
=> fix: Error caused by converting `hardBreak` nodes

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/HyperlinkToolbar/HyperlinkToolbarPlugin.ts, packages/react/src/FormattingToolbar/components/LinkToolbarButton.tsx
The formatting toolbar is supposed to hide if the editor blurs, unless the element the focus is moving to is the formatting toolbar itself. The condition which checked for this was incorrect, and instead checked if the focus moved to any descendant of the formatting toolbar's parent element. Since the formatting toolbar gets appended to the `doc`, it meant that the toolbar would not be closed if clicking on any element inside the `doc`.
Closes #161
TODO:
- Link creation menu inputs are not selectable if the popup is appended to the button. Has to be appended to `document.body` to select inputs with the mouse. Because of that, toolbar disappears since popup is not a descendant. There is an easy fix but it's extremely ugly.
=> fix: Formatting Toolbar not hiding when clicking on elements outside it

.gitignore, examples/editor/tsconfig.json, examples/vanilla/tsconfig.json, packages/react/tsconfig.json, packages/website/tsconfig.json
This should enable IDE hints for typescript types across packages, without requiring a new build
Discussed on discord: https://discord.com/channels/928190961455087667/1015169282444894219/1119898650231971921
=> chore: setup typescript project references so IDE shows hints

packages/website/docs/docs/block-types.md, packages/website/docs/docs/blocks.md, packages/website/docs/docs/formatting-toolbar.md, packages/website/docs/docs/side-menu.md, packages/website/docs/docs/slash-menu.md
This PR fixes screenshots for the documentation webisite
=> fix: Documentation site screenshots

package.json
because we were getting this message when playwright runs:
```
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.35.1. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.33.0-focal               ║
║ - required: mcr.microsoft.com/playwright:v1.35.1-focal               ║
║                                                                      ║
║ <3 Playwright Team                                                   ║
╚══════════════════════════════════════════════════════════════════════╝
```
Updates from `mcr.microsoft.com/playwright:v1.33.0-focal` to `mcr.microsoft.com/playwright:v1.35.1-focal`
=> fix: update playwright image

packages/react/src/ReactBlockSpec.tsx, packages/website/docs/docs/block-types.md, tests/utils/customblocks/ReactAlert.tsx
We should provide the ability to render `InlineContent` to elements other than `div`s in the DOM. It's already possible to do this in vanilla JS, and technically also in React, but an `as` prop needs to be added to the `InlineContent` component. This small PR does that.
=> feat: Ability to change base HTML element `InlineContent` component 

examples/vanilla/src/ui/blockSideMenuFactory.ts, examples/vanilla/src/ui/formattingToolbarFactory.ts, examples/vanilla/src/ui/hyperlinkToolbarFactory.ts, examples/vanilla/src/ui/slashMenuFactory.ts, packages/core/src/extensions/DraggableBlocks/BlockSideMenuFactoryTypes.ts, packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarFactoryTypes.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/HyperlinkToolbar/HyperlinkToolbarFactoryTypes.ts, packages/core/src/extensions/HyperlinkToolbar/HyperlinkToolbarPlugin.ts, packages/core/src/shared/EditorElement.ts, packages/core/src/shared/plugins/suggestion/SuggestionPlugin.ts, packages/core/src/shared/plugins/suggestion/SuggestionsMenuFactoryTypes.ts, packages/react/src/BlockNoteTheme.ts, packages/react/src/ElementFactory/components/EditorElementComponentWrapper.tsx, packages/react/src/ElementFactory/components/ReactElementFactory.tsx
Right now, every time we scroll, each `uiElement` is re-rendered. In general, I do think we want to leave the responsibility of figuring out when to render/hide `uiElement`s completely up to BlockNote, Tippy has it's own listeners to figure out when it should update its position. Trying to re-render the whole component on scroll instead of letting Tippy sort it out itself leads to some issues, namely overflow handling and bad responsiveness.
https://discord.com/channels/928190961455087667/1015169282444894219/1120228729600348181
https://discord.com/channels/928190961455087667/1015169282444894219/1120355999828680795
=> fix: Scrolling responsiveness & UI element overflow

packages/core/src/extensions/Blocks/nodes/BlockContainer.ts, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspacePreservesMarks-json-chromium-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspacePreservesMarks-json-firefox-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspacePreservesMarks-json-webkit-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspacePreservesNestedBlocks-json-chromium-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspacePreservesNestedBlocks-json-firefox-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspacePreservesNestedBlocks-json-webkit-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspaceStartOfBlock-json-chromium-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspaceStartOfBlock-json-firefox-linux.json, tests/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/backspaceStartOfBlock-json-webkit-linux.json
=> fix: keep marks when merging blocks

packages/core/src/BlockNoteEditor.ts
This PR makes it so that `onEditorContentChange` and `onTextCursorPositionChange` are only called after the editor has been initialized and `initialContent` has been set.
=> fix: `onEditorContentChange` and `onTextCursorPositionChange` firing before editor is initialized

examples/editor/src/main.tsx, packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/HyperlinkToolbar/HyperlinkToolbarPlugin.ts, packages/core/src/extensions/SlashMenu/SlashMenuPlugin.ts, packages/core/src/shared/plugins/suggestion/SuggestionPlugin.ts, packages/react/src/BlockNoteView.tsx, packages/react/src/BlockSideMenu/components/BlockSideMenu.tsx, packages/react/src/FormattingToolbar/components/FormattingToolbar.tsx, packages/react/src/HyperlinkToolbar/components/HyperlinkToolbar.tsx, packages/react/src/SharedComponents/Toolbar/components/ToolbarDropdown.tsx, packages/react/src/SlashMenu/components/SlashMenu.tsx, packages/website/partykitserver.ts
This addresses several issues in #270"
- call unregisterPlugin as useEffect disposer
- fixed event listener removal + reverted the plugin view instantation
- now, strict mode works again
- remove tippy `appendTo`, this is possible because I made the elements children of EditorView, and included a <div/> within the <Tippy> components
- cleaned up the referenceRect logic a bit
=> several fixes for react rearchitecture

README.md
Closes https://github.com/TypeCellOS/BlockNote/issues/284
=> add license explanation

packages/core/src/BlockNoteEditor.ts, packages/core/src/extensions/UniqueID/UniqueID.ts, packages/react/src/BlockNoteView.tsx, packages/react/src/hooks/useBlockNote.ts
with this change we:
- explicitly pass initial content of the editor, so that we can make sure the default paragraph has an `id`
- disable uniqueId onCreate(). As this is disabled for collab anyway, I think it's cleaner to clear this. It also was causing issues with unit tests.
- we don't need to call `replaceBlocks` in onCreate anymore 🎉
=> fix initialcontent and uniqueid

packages/core/src/extensions/Blocks/helpers/getBlockInfoFromPos.ts
`getBlockInfoFromPos` previously returned `undefined` if the position was outside the outermost block group. This edge case is now handled properly, so the function always returns an object.
=> fix: `getBlockInfoFromPos` no longer returns `undefined`

.eslintrc.js, examples/editor/package.json, examples/vanilla/package.json, lerna.json, package-lock.json, package.json, packages/core/package.json, packages/react/package.json, packages/website/package.json
During the investigation of #276 I found an issue (doesn't solve the original issue), that tippy.js is bundled in our bundled javascript files.
This is because vite is configured to not bundle dependencies listed in packages.json. However, we import "tippy.js" in our formattingtoolbar, but it's not in the package json.
This PR:
- fixes the above issue by including "tippy.js" as a depdency
- also upgrades vite
We can prevent these errors by using https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md. @matthewlipski, could you look into adding this eslint rule?
=> fix: include tippy dependency

packages/core/src/BlockNoteEditor.ts
https://github.com/TypeCellOS/BlockNote/pull/289 introduced a bug for collaboration.
This line https://github.com/yjs/y-prosemirror/blob/6349748b44859eacb8e54ef94757e2f59bb89113/src/plugins/sync-plugin.js#L193C20-L193C20 would evaluate to true, making y-prosemirror think the user changed the initialcontent intentionally.
This basically always reset the editor to an empty state
=> fix: collaboration initial content bug

packages/website/docs/docs/nextjs.md
It seems like `dynamic` is also needed when using the app router
=> docs: fix nextjs docs

packages/core/src/extensions/UniqueID/UniqueID.ts
This should fix a bug when building blocknote in nextjs. It also cleans up the code a bit
Closes #301
=> fix: don't call window if not defined for nextjs

packages/website/docs/.vitepress/theme/components/Examples/BlockNote/ReactBlockNote.module.css, packages/website/docs/.vitepress/theme/components/Examples/BlockNote/ReactBlockNote.tsx
After improving the theming and styling of BlockNote, I forgot to update the home page demo to work with the new theme API, so this PR fixes that.
=> fix: Homepage dark theme

packages/core/src/BlockNoteExtensions.ts, packages/core/src/api/formatConversions/formatConversions.ts
Two small changes I need for TypeCell:
- change the HTML that is output when parsing codeblocks in markdown
- Make the collaboration provider optional
These are currently needed to import markdown sources into TypeCell. A better fix would be to make this customizable externally and not having to instantiate a BlockNoteEditor to import / export markdown, but for now this kind of works
=> fix: make collab provider optional and change output of code blocks

packages/react/src/FormattingToolbar/components/DefaultDropdowns/BlockTypeDropdown.tsx, packages/react/src/FormattingToolbar/components/DefaultFormattingToolbar.tsx, packages/react/src/SharedComponents/Toolbar/components/ToolbarDropdown.tsx
This PR makes the block type dropdown more customizable. Both it, and the default formatting toolbar, take an `items` prop which you can replace the items with. The object type has also been much simplified, and a default list of items is provided.
=> feat: Improved block type dropdown customization

packages/core/src/api/nodeConversions/nodeConversions.ts, packages/core/src/extensions/Blocks/helpers/getBlockInfoFromPos.ts
A recent change has broken custom blocks which don't contain inline content. This is because we added edge case handling in `getBlockInfoFromPos`, for situations where the selection is outside of any blocks. However, `nodeToBlock` was unnecessarily and incorrectly calling `getBlockInfoFromPos` with the `blockContainer` node instead of the `doc`, and was causing errors when inserting custom blocks without inline content.
Closes #300
=> fix: Custom blocks without inline content

.github/workflows/build.yml
I saw some warnings in GH Actions related to outdated config. This should fix them
=> chore: upgrade github actions

packages/core/src/extensions/Blocks/nodes/BlockContainer.ts
This PR brings the UX slightly more inline with Notion by changing the behaviour when pressing Enter at the start of a block. Before, it would copy the content to a new block below but the new block would always be a paragraph. Now, the block's type is also copied over.
=> fix: Enter preserves block type when text cursor is at the start of a block

packages/core/src/shared/plugins/suggestion/SuggestionPlugin.ts
=> fix: Slash menu error when hitting enter with no items

packages/core/src/extensions/Blocks/nodes/BlockContainer.ts
This PR adds Delete key handling, allowing you to merge the current block with the next one when the cursor is in certain positions. The exact logic how/when this happens is documented in the code. Not sure the UX is 100% there so feedback is welcome, and not sure what to do when the block the cursor is in has children.
=> feat: Delete key handling

packages/react/src/SideMenu/components/DragHandleMenu/DefaultButtons/BlockColorsButton.tsx, packages/react/src/SideMenu/components/DragHandleMenu/DragHandleMenuItem.tsx, packages/website/docs/docs/side-menu.md
=> feat: Add Drag Handle Menu item `closeMenuOnClick` prop

packages/website/docs/.vitepress/config.ts, packages/website/docs/examples/changing-font.md
This PR adds an example for changing the editor font and provides a few key CSS selectors that can be used to change the styling of specific parts of the editor.
=> docs: Example for changing editor font

packages/core/src/extensions/Blocks/nodes/Block.module.css, packages/core/src/extensions/Blocks/nodes/BlockContent/ImageBlockContent/ImageBlockContent.ts
=> fix: Image blocks resizable when editor isn't editable

packages/website/docs/examples/saving-loading.md
The current saving-loading page info is not the correct
=> fix: saving-loading meta info

packages/core/src/BlockNoteEditor.ts
Currently, some fields passed in the `_tiptapOptions` editor option are completely overwritten, such as `onCreate`, and `onUpdate`. This PR fixes this so that both options passed in `_tiptapOptions` and the remaining editor options are applied. BlockNote options take priority over TipTap options for fields that take primitive values. For fields that take objects/arrays, the options are merged. Closes #389
=> fix: `_tiptapOptions` typing and fields getting overridden

examples/editor/src/main.tsx, packages/core/src/BlockNoteEditor.ts, packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
fixes https://github.com/TypeCellOS/BlockNote/issues/366
and `Uncaught TypeError: Cannot read properties of null (reading 'id')` when hovering over an empty block when using collaboration (reported via discord)
yjs calls `createAndFill` here: https://github.com/yjs/y-prosemirror/blob/e0e5e951614abe1be2295e5ab8987ab5916bcaec/src/plugins/sync-plugin.js#L194
=> fix: block id null when using collaboration

packages/core/src/api/blockManipulation/blockManipulation.ts
=> fix: Bug in `replaceBlocks`

packages/core/src/api/blockManipulation/blockManipulation.ts, packages/core/src/editor/BlockNoteEditor.ts
This PR adds return values for the following `BlockNoteEditor` methods:
```
// Returns the blocks after being inserted
insertBlocks(...): Block[]
// Returns the updated block
updateBlock(...): Block
// Returns the blocks that were removed
removeBlocks(...): Block[]
// Returns both the blocks that were removed and the blocks after being inserted
replaceBlocks(...): {
insertedBlocks: Block[];
removedBlocks: Block[];
}
```
Closes #410
=> feat: Return values for block manipulation methods

packages/core/src/editor/Block.css
This PR fixes the lists indentation in case of multi-line content.
- Closes #463 
There are some formatting changes which were popping on saving the CSS file. Tried avoid them, but were overwritten.
**Previously**
**Updated**
=> fix: Multiline list indentation

packages/core/src/api/parsers/pasteExtension.ts
This PR removes console.log generated while pasting content from clipboard
- closes #477
=> fix: Remove console logs while pasting

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
This PR makes the add block button always create a new block below for blocks with table content and no content.
=> fix: Add block button behaviour on blocks with different content

packages/core/src/blocks/ImageBlockContent/ImageBlockContent.ts
=> fix: Errors when hovering image block while editor is uneditable

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts
=> fix: Formatting toolbar not hiding while dragging blocks

examples/editor/package.json, packages/core/package.json, packages/react/package.json
This update should help to mitigate the issues from #523. While Mantine still sets some global styles in 7.4.2, there is not much we can do to reset these styles ourselves (see #525 for an attempt of that).
=> chore: Mantine 7.4.2

packages/core/src/blocks/ParagraphBlockContent/ParagraphBlockContent.ts, packages/core/src/pm-nodes/BlockContainer.ts
=> fix: Paragraph shortcut

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/util/browser.ts, packages/react/src/components/mantine-shared/Toolbar/ToolbarButton.tsx, packages/react/src/components/mantine-shared/Toolbar/ToolbarDropdownTarget.tsx
Apparently, buttons are not focused on click in Safari (https://stackoverflow.com/questions/61245883/why-blur-and-focus-doesnt-work-on-safari). Since we use a blur event handler to hide the formatting toolbar sometimes, this wasn't working which caused the link button and block type dropdown to close the formatting toolbar on click. This PR forces toolbar buttons to become focused on mouse down, which fixes the issue. Doesn't seem to be a problem for other UI elements.
closes https://github.com/TypeCellOS/BlockNote/issues/530
=> fix: Safari toolbar buttons & dropdowns

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
L 290 shows mousemove event is use capure, but destroy not use it, it makes remove not work.
Issue 603 is caused by this bug.
closes https://github.com/TypeCellOS/BlockNote/issues/603
=> Fix remove 'mousemove' event listener

CONTRIBUTING.md
https://github.com/TypeCellOS/BlockNote/blob/main/packages/core/ARCHITECTURE.md
is now already replaced by
https://github.com/TypeCellOS/BlockNote/blob/main/packages/core/src/pm-nodes/README.md
and `ARCHITECTURE.md` is already deleted.
=> chore: Replace link to file of Architecture

docs/components/pages/landing/gradients.css, docs/components/pages/landing/hero/Demo.tsx, docs/components/pages/landing/hero/DemoEditor.tsx, docs/components/pages/landing/hero/Hero.tsx, docs/components/pages/landing/hero/Text.tsx, docs/components/pages/landing/hero/styles.css, docs/components/pages/landing/shared/Headings.tsx, docs/components/pages/landing/styles.css, examples/01-basic/04-selection-blocks/App.tsx
This PR hides the editor below a certain screen size and fixes z-index of hamburger menu
=> docs: Mobile fixes

packages/core/src/editor/BlockNoteEditor.ts
We were always triggering `setEditable` even if this wasn't necessary. This triggered an `onChange` before the view was mounted
fixes #622
=> fix: don't call `setEditable` when not necessary

packages/core/src/api/getCurrentBlockContentType.ts, packages/core/src/blocks/HeadingBlockContent/HeadingBlockContent.ts, packages/core/src/blocks/ListItemBlockContent/BulletListItemBlockContent/BulletListItemBlockContent.ts, packages/core/src/blocks/ListItemBlockContent/NumberedListItemBlockContent/NumberedListItemBlockContent.ts, packages/core/src/blocks/ParagraphBlockContent/ParagraphBlockContent.ts
This PR adds a temp fix which blocks keyboard shortcuts and input rules from firing in table blocks. However, we should look to fix selections and make this work for multiple blocks (see #560 for more info).
Closes #555
=> fix: Keyboard shortcuts & input rules in tables

packages/core/src/editor/editor.css
Besides being bad practice, using `all: unset` in the default styles causes issues with keystrokes when the text cursor is at the start of a block, before non-editable inline content. I think we can just remove it as it doesn't seem to cause any styling issues.
=> fix: Remove `all: unset` from default styles

packages/core/src/extensions/SuggestionMenu/getDefaultSlashMenuItems.ts
Notion menu item filtering 
Current BlockNote filtering only matches start of the word. This PR fixes it to match query anywhere in the item or alias text
=> fix: match query anywhere to filter slash menu items

packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/NonEditableBlocks/NonEditableBlockPlugin.ts
This PR improves how keystrokes are handled in non-editable blocks like images, so that more edge cases are covered (including special characters like ś and Enter).
A more robust approach might be to filter out transactions in which a no content block is selected before, and replaced with a paragraph block after (will likely need additional filtering e.g. to not filter out `updateBlock` calls). However, I think the current implementation gets us 90% of the way there with much less complexity so I don't think it's worth looking into.
TODO: We should merge the `releases` branch into main first
=> fix: Key inputs in blocks without content

docs/pages/docs/advanced/nextjs.mdx, examples/02-ui-components/05-side-menu-drag-handle-items/App.tsx, examples/02-ui-components/05-side-menu-drag-handle-items/ResetBlockTypeItem.tsx
This PR fixes a crash caused by the custom drag handle menu items example and updates the NextJS docs to reflect changes in the most recent BlockNote version.
=> docs: Minor docs fixes

packages/core/src/i18n/locales/index.ts, packages/core/src/i18n/locales/pt-BR.ts
- Adding the pt-BR translation file to the @blocknote/core package
=> feat: add i18n support for Brazilian Portuguese (pt-BR)

packages/core/src/i18n/locales/index.ts, packages/core/src/i18n/locales/is.ts, packages/core/src/i18n/locales/pl.ts
- Added `is.ts` and `pl.ts` i18n files.
=> feat: add i18n support for pl-PL and is-IS

packages/core/src/i18n/locales/zh.ts
fix https://github.com/TypeCellOS/BlockNote/issues/779
before:
now:
=> fix: update zh.ts

packages/mantine/src/index.tsx
=> fix: Remove `data-mantine-color-scheme` attribute

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
Almost always, the side menu only needs to update when the mouse cursor moves. However, in some edge cases, such as the delete side menu button, the block or block position changes without the mouse moving. This PR makes the side menu also update after editor state updates if needed.
Closes #580
=> fix: Side menu not updating in edge cases

packages/core/src/blocks/ListItemBlockContent/ListItemKeyboardShortcuts.ts, packages/core/src/blocks/ParagraphBlockContent/ParagraphBlockContent.ts, packages/core/src/editor/Block.css, packages/core/src/extensions/Placeholder/PlaceholderPlugin.ts, packages/core/src/pm-nodes/BlockContainer.ts
Closes #643 
Also fixes edge cases where a block contains only a piece of non-editable inline content and Enter is pressed. Previously this inline content was ignored as the enter handlers only checked for text content.
=> fix: Custom inline content placeholder bug and enter handling

packages/core/src/extensions/FilePanel/FilePanelPlugin.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/LinkToolbar/LinkToolbarPlugin.ts, packages/core/src/extensions/SideMenu/SideMenuPlugin.ts, packages/core/src/extensions/SuggestionMenu/SuggestionPlugin.ts, packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts
This PR fixes UI elements like the formatting toolbar and side menu only scrolling with the editor when the whole page is being scrolled. Now, the elements scroll with the editor regardless of which containing element is being scrolled. Additionally, the side menu is now hidden on click after being frozen, to more closely replicate Notion's UX.
Closes #748
=> fix: UI element position on scroll

packages/mantine/src/menu/Menu.tsx
Right now, Mantine sub-menu dropdowns are being rendered within the menu item that opens them. This throws an error as the menu item is a button, and the dropdown contains more menu items which are also buttons (`button` elements are not valid descendants of other `button` elements).
This PR makes sub menu dropdowns get rendered in the same dropdown as the menu items which trigger them, same as how Ariakit and ShadCN do it.
=> fix: Mantine sub-menu rendering in the DOM

packages/core/src/api/parsers/pasteExtension.ts, packages/core/src/editor/Block.css, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/extensions/FilePanel/FilePanelPlugin.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/react/src/components/FormattingToolbar/DefaultButtons/BasicTextStyleButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/ColorStyleButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/CreateLinkButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/FileCaptionButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/FileDeleteButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/FilePreviewButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/FileRenameButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/FileReplaceButton.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/NestBlockButtons.tsx, packages/react/src/components/FormattingToolbar/DefaultButtons/TextAlignButton.tsx, packages/react/src/components/FormattingToolbar/DefaultSelects/BlockTypeSelect.tsx
Closes #707
Closes #770
Closes #766
=> fix: Issues when editor is non-editable

packages/shadcn/src/style.css
We have a CSS rule to remove the focus ring from focused elements in ShadCN that is scoped globally instead of to the editor, which this PR fixes.
Closes #787
=> fix: Removed ShadCN focus global CSS

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts, packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts, tests/src/end-to-end/dragdrop/dragdrop.test.ts, tests/src/end-to-end/shadcn/shadcn.test.ts
This PR simplifies & fixes logic in the side menu used to find the hovered block. Specifically, this fixes an error that gets thrown in the built environment when the hovered block isn't found, and makes the behaviour consistent for both the dev and built envs.
=> fix: Side menu block finding logic

playground/src/style.css
The margin of block in playground pages has a bug that causes the block to go out of the small screen. This PR fixed it.
https://github.com/TypeCellOS/BlockNote/assets/38809606/7c4d6ce6-a6ec-4261-b0b5-cb8e85d75d95
=> fix: fix margin of block of playground in small screen

packages/react/src/schema/@util/ReactRenderUtil.ts
Fixes https://github.com/TypeCellOS/BlockNote/issues/750
**Before**
**After**
=> fix: Custom inline content crash

packages/core/src/i18n/locales/ar.ts, packages/core/src/i18n/locales/index.ts
Salam 👋,
This PR simply adds Arabic translations.
Handling RTL isn't yet implemented and I will have to study the code a little more to know how to add that feature. If mantine is used then we could perhaps use the mantine [`DirectionProvider`](https://mantine.dev/styles/rtl/#directionprovider)
=> feat(i18n): add Arabic translation

examples/01-basic/10-localization/App.tsx
I couldn't figure out how to add additional text under the preview block so I just added comments to the actual preview block.
The comments I added simply show how to use dynamic language in TS with 
```ts
dictionary: locales[lang as keyof typeof locales]
```
=> chore(docs): include comments about dynamic locales in TS

packages/core/src/api/exporters/markdown/__snapshots__/lists/basic/markdown.md, packages/core/src/api/exporters/markdown/__snapshots__/lists/nested/markdown.md, packages/core/src/api/exporters/markdown/markdownExporter.ts
Fixes #834 
---
For some reason, returning the text node within the `remarkStringify` handler option solved the issue with an extra backslash before the first bracket. 
```ts
.use(remarkStringify, { handlers: { text: (node) => node.value } })
```
=> fix: update `remarkStringify` config

packages/mantine/src/index.tsx, packages/react/src/editor/BlockNoteView.tsx
usePrefersColorScheme is exported from use-prefers-color-scheme as named function and default
importing usePrefersColorScheme as named function will help in fixing the webpack 5 issue #860
=> Fix: [#860] TypeError: use_prefers_color_scheme__ is not a function

packages/shadcn/src/form/TextInput.tsx, packages/shadcn/src/style.css, packages/shadcn/src/tailwindStyles.css, packages/shadcn/tailwind.config.js
This PR fixes ShadCN style scoping to only affect elements in `.bn-container` and fixes an error being thrown on editor init.
Closes #880
Closes #749
=> fix: ShadCN styles scoping & ref error

package-lock.json, packages/mantine/package.json, packages/mantine/src/index.tsx, packages/react/package.json, packages/react/src/editor/BlockNoteView.tsx, packages/react/src/hooks/usePrefersColorScheme.ts, packages/react/src/index.ts
The `use-prefers-color-scheme` dependency is still causing issues in some NextJS projects. Since the import is really only one source file for the `usePrefersColorScheme` hook, this PR copies the code to a local file in `react`, omitting the dependency altogether.
=> refactor: Removed `use-prefers-color-scheme` dependency

packages/core/src/editor/editor.css, packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
This PR fixes 2 issues with the drag preview for blocks:
1. Fixes a regression made in #849 where the preview element was added to the DOM on drop instead of removed, cluttering the DOM with each drop.
2. Fixes an edge case where drag previews were incorrectly displayed due to the preview element being outside of the editor.
=> fix: Drag preview issues

packages/core/src/i18n/locales/en.ts
=> fix: Strikethrough shortcut in formatting toolbar button tooltip

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
Seems like `freezeMenu` was not actually fully freezing the side menu, as `mousemove` events were still being handled as normal and dispatching updates when they should be ignored.
Closes #911
=> fix: Side menu not actually freezing

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
Even though the drop cursor still appears when the mouse cursor is beyond the editor vertically, letting go of the mouse button doesn't actually trigger a drop in the editor. This PR fixes that by restricting the mouse cursor y-coordinate to the editor's bounding box on drop.
Closes #934
=> fix: Dropping blocks above editor

CONTRIBUTING.md
Simply adds a table in `contribution.md` to show the packages. 
This table can also be added to the primary readme.md if you'd like, for easy access to npm links of each of the packages.
---
On a side note, it seems the "Directory Structure" section is outdated regarding the examples folders
=> docs: update contribution.md to include a table of packages

README.md
Simply fixes the link to examples in the readme header
=> docs: examples link in `readme.md`

packages/core/src/extensions/SuggestionMenu/getDefaultEmojiPickerItems.ts
temporary fix following this solution: https://stackoverflow.com/questions/76767943/how-to-import-esm-libraries-without-setting-type-module-in-package-json-fil
- root cause in emoji-mart: https://github.com/missive/emoji-mart/pull/929
=> fix: emojimart import

packages/core/src/editor/editor.css
Even though we've tried different approaches, we still keep seeing people have issues with the drag preview. Here's a summary of the things we've tried before and why they weren't ideal:
This is [recommended by Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage):
> Note: If the [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) is an existing [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) it needs to be visible in the viewport in order to be shown as a drag feedback image. Alternatively, you can create a new DOM element that might be off-screen specifically for this purpose.
It works for most cases but isn't 100% reliable, as it causes bugs with some apps (@YousefED this was specifically an issue with …
=> fix: Drag preview visibility

packages/dev-scripts/examples/gen.ts, packages/dev-scripts/examples/genDocs.ts, packages/dev-scripts/examples/util.ts, packages/dev-scripts/package.json
=> fix: windows gen file

docs/components/pages/pricing/faq.tsx, docs/components/pages/pricing/tiers.tsx, docs/pages/pricing.mdx
blocknote always remains free and open source, but let's focus the pricing page on paid subscriptions
=> docs: remove free tier on pricing page

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
`getDraggableBlockFromElement` currently goes up the DOM tree until it finds an element with the `data-id` attribute, which it assumes to be a block. This is incorrect, as the `data-id` attribute can also come up in custom inline content and styles, so this PR changes it to ensure the attribute checked always belongs to a block.
Closes #863
=> fix: Attribute check in `getDraggableBlockFromElement`

packages/core/src/index.ts
Right now, the only way to extend default blocks is to redefine them entirely, using most of the existing code. While we should figure out a proper API for extending blocks at some point, right now it's not possible to even redefine the default vanilla blocks as some exports are missing. This PR adds them.
=> fix: Add exports for vanilla block helpers

packages/react/src/components/SuggestionMenu/SuggestionMenuController.tsx
This PR slightly changes how the suggestion menu is positioned to better handle horizontal overflows on small screens. It now moves only enough to prevent the overflow, instead of getting flipped to the other side of the text caret and potentially causing an overflow on the other side.
=> fix: Slight improvement to suggestion menu positioning

docs/pages/docs/editor-basics/setup.mdx
Fixed incorrect link for emojiPicker documentation.
Updated the emojiPicker link in the docs from (/docs/ui-components/suggestion-menus#emoji-picker) to (/docs/advanced/grid-suggestion-menus#emoji-picker), which is the correct URL.
=> docs: Fix Emoji Picker link

packages/react/src/components/SuggestionMenu/GridSuggestionMenu/hooks/useGridSuggestionMenuKeyboardNavigation.ts, packages/react/src/components/SuggestionMenu/hooks/useSuggestionMenuKeyboardNavigation.ts
Any languages with composition sessions (Korean, Japanese, etc..) have `isComposing` at keydown events.
Because of this, using the Korean suggestion make two same blocks(ex. /이미지, /구분선).
(If you press Enter after typing Korean, the keyDown event is fired both when the isComposing state is true and when it is false, resulting in two blocks with duplicate events.)
to prevent this situation, checking `event.isComposing` is necessary.
by simply adding checking `event.isCompoising == false`, We can prevent making blocks twice when using Korean.
here is the MDN page that explains `isComposing`
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing
=> fix: Block insert twice when using korean at suggestion

docs/pages/docs/editor-basics/default-schema.mdx
`TableContent[]` is wrong
`TableContent` is correct
=> Update Doc: table's content type is TableContent

packages/core/src/api/parsers/handleFileInsertion.ts, packages/core/src/blocks/AudioBlockContent/AudioBlockContent.ts, packages/core/src/blocks/ImageBlockContent/ImageBlockContent.ts, packages/core/src/blocks/VideoBlockContent/VideoBlockContent.ts, packages/core/src/schema/blocks/types.ts, packages/react/src/components/FilePanel/DefaultTabs/UploadTab.tsx
This PR fixes 2 issues with dropping and pasting external files into the editor.
First, the files are now always inserted as new blocks instead of updating existing ones, and also dropping has been fixed to use the block under the mouse cursor instead of the currently selected one.
Second, using file extensions in a file block's `fileBlockAcceptMimeTypes` was throwing errors before, and is now fixed. File extensions and MIME types are now checked independently, whereas before, file extensions were just treated as MIME types causing some logic to fail.
=> fix: External file drag/drop and copy/paste

package-lock.json
https://www.cve.org/CVERecord?id=CVE-2024-4067
> The NPM package micromatch prior to 4.0.8 is vulnerable to Regular Expression Denial of Service (ReDoS). The vulnerability occurs in micromatch.braces() in index.js because the pattern .* will greedily match anything. By passing a malicious payload, the pattern matching will keep backtracking to the input while it doesn't find the closing bracket. As the input size increases, the consumption time will also increase until it causes the application to hang or slow down. There was a merged fix but further testing shows the issue persists. This issue should be mitigated by using a safe pattern that won't start backtracking the regular expression due to greedy matching. This issue was fixed in version 4.0.8.
=> vulnerability found in micromatch. bump version to 4.0.8

packages/react/src/components/FormattingToolbar/DefaultButtons/FileDownloadButton.tsx, packages/react/src/components/LinkToolbar/DefaultButtons/OpenLinkButton.tsx, packages/react/src/util/sanitizeUrl.ts
There is an XSS vulnerability in the file upload and link toolbar features.
To reproduce, create a file embed or a link with `javascript:alert(origin)`. Click on the download / open button, and `alert(origin)` will be run in the user's browser.
This fixes the XSS vulnerability by providing a sensible default when the protocol is `javascript:`.
=> fix: xss in link toolbar and file download

packages/react/src/components/SuggestionMenu/SuggestionMenuController.tsx
In #984, we added the ignoreQuery state, and I think it applies `SuggestionMenuController` as well
=> feat: SuggestionMenuController.tsx support ignoreQueryLength

packages/core/src/api/exporters/copyExtension.ts
This PR adds basically the same logic for cut events as already exists or copy events, as currently only copies are properly handled.
Closes #1067 
Closes #813
=> fix: Cut events when a block is selected

examples/01-basic/01-minimal/App.tsx, packages/core/src/editor/BlockNoteEditor.test.ts, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/UniqueID/UniqueID.ts
This PR adds a the option to set the html id on each block. This can then be used for anchors in a table of contents.
=> feat: add option to set html id

docs/pages/docs/editor-basics/setup.mdx, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/pm-nodes/BlockContainer.ts
closes https://github.com/TypeCellOS/BlockNote/issues/1058
=> add option to disable animations

packages/core/src/schema/blocks/createSpec.ts, packages/core/src/schema/blocks/types.ts, packages/react/src/schema/ReactBlockSpec.tsx
This PR adds the `isSelectable` field to block configs which allows the block to not be selectable. This is an optional field which is true by default.
=> feat: Non-selectable custom blocks

packages/core/src/schema/blocks/createSpec.ts
It seems pointless to let the editor handle any events within a non-selectable block, as these are basically islands of content that aren't handled by ProseMirror.
This fix is mainly done as keyboard events may still be handled by PM before reaching the DOM - I noticed this was causing some issues in the DO database block.
=> fix: Made all events in non-selectable blocks get handled by browser

packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts
I experimented with a few different methods of achieving this, but this was the solution that gave the best UX while also adding not much complexity.
=> fix: Table handles hide when selection is active

docs/pages/docs/ui-components/image-toolbar.mdx
=> docs: Fixed image upload demo

packages/core/src/api/clipboard/__snapshots__/tableAllCells.html, packages/core/src/api/clipboard/clipboard.test.ts, packages/core/src/api/clipboard/toClipboard/copyExtension.ts, packages/core/src/api/exporters/html/externalHTMLExporter.ts, packages/core/src/api/exporters/html/htmlConversion.test.ts, packages/core/src/api/exporters/html/internalHTMLSerializer.ts, packages/core/src/api/exporters/html/util/sharedHTMLConversion.ts, packages/core/src/api/nodeConversions/fragmentToBlocks.ts, packages/core/src/api/nodeConversions/nodeConversions.ts, packages/core/src/extensions/SideMenu/SideMenuPlugin.ts, packages/server-util/src/context/react/ReactServer.test.tsx
This PR refactors the serialization logic and removes our trick of "hacking" the prosemirror serializer.
Instead, we create our own serialization logic. This will result in a cleaner codebase and also make it easier to make changes to the underlying prosemirror schema and add other serializers
=> refactor: cleaned serialization code

packages/core/src/api/blockManipulation/__snapshots__/blockManipulation.test.ts.snap, packages/core/src/api/blockManipulation/blockManipulation.test.ts, packages/core/src/pm-nodes/BlockContainer.ts
=> fix: Block update removing children when setting content

packages/ariakit/package.json, packages/core/package.json, packages/react/package.json, packages/server-util/package.json, packages/shadcn/package.json
correctly set sideeffects for all packages.
closes https://github.com/TypeCellOS/BlockNote/pull/1144
earlier context: https://github.com/TypeCellOS/BlockNote/pull/801
=> chore: mark all css files as sideEffects

packages/core/src/extensions/KeyboardShortcuts/KeyboardShortcutsExtension.ts
In one of the Delete keyboard handlers, we call `getPrevBlockPos` before checking if a previous block exists in the document, leading to an error being thrown.
closes https://github.com/TypeCellOS/BlockNote/issues/1167
=> fix: Error thrown on Backspace in first block

packages/core/src/blocks/TableBlockContent/TableBlockContent.ts
fixes this issue:
https://github.com/user-attachments/assets/edec7c8c-244e-4d1b-b3db-299adb94e032
I also tried to fix #1077 at the same time, (this happens when trying to paste HTML content that's more than a single element, but this is quite a bit more involved unfortunately,
=> fix: pasting in table

packages/core/src/blocks/FileBlockContent/fileBlockHelpers.ts
Fix caption width issue it now able to sync when reizing.
The way fix it just to set same width, but this might not perfect solution.
_Note: potential problem:_
- when caption trim by white space, it will go another line, but we cant decide when it change line.
- due to same pixel, it might not good when we have some element on left or right overlapped.(this can be fix if have proper padding for caption paragraph tag)
- I notice when it resize it will actualy re-render the whole block container, this can be improve.
https://github.com/user-attachments/assets/6346a338-7291-488e-b430-dad674e3c8cd
=> fix: caption width match file container #1169

packages/core/src/editor/BlockNoteTipTapEditor.ts
this should fix strict mode on react 19 / next 15
closes https://github.com/TypeCellOS/BlockNote/issues/1145
=> fix: react 19 strictmode race condition

docs/components/example/styles.css
Nextra adds some styling to `code` elements which breaks code blocks inside the editor, so this PR fixes that
=> docs: Fixed code block styling in demos

packages/core/src/api/blockManipulation/commands/moveBlock/moveBlock.test.ts, packages/core/src/api/blockManipulation/commands/splitBlock/splitBlock.ts, packages/core/src/api/clipboard/fromClipboard/handleFileInsertion.ts, packages/core/src/api/getBlockInfoFromPos.ts, packages/core/src/blocks/HeadingBlockContent/HeadingBlockContent.ts, packages/core/src/blocks/ListItemBlockContent/BulletListItemBlockContent/BulletListItemBlockContent.ts, packages/core/src/blocks/ListItemBlockContent/CheckListItemBlockContent/CheckListItemBlockContent.ts, packages/core/src/blocks/ListItemBlockContent/ListItemKeyboardShortcuts.ts, packages/core/src/blocks/ListItemBlockContent/NumberedListItemBlockContent/NumberedListItemBlockContent.ts, packages/core/src/blocks/ParagraphBlockContent/ParagraphBlockContent.ts, packages/core/src/editor/BlockNoteEditor.test.ts, packages/core/src/extensions/KeyboardShortcuts/KeyboardShortcutsExtension.ts, packages/xl-multi-column/src/extensions/DropCursor/MultiColumnDropCursorPlugin.ts
Closes #1237 
Currently, `getNearestBlockContainerPos` gets the nearest block, which may be a `columnList`, `column`, or `blockContainer`. I think the functionality is fine, but this PR renames it to `getNearestBlockPos` for better clarity and removes the error in `getBlockInfoFromSelection` for when something other than a `blockContainer` is returned. This fixes a bug that caused said error to be thrown by selecting a `column` node using triple click (I think) or Cmd+click.
=> fix: `getNearestBlockContainerPos` unclear

packages/core/src/blocks/ListItemBlockContent/BulletListItemBlockContent/BulletListItemBlockContent.ts, packages/core/src/blocks/ListItemBlockContent/CheckListItemBlockContent/CheckListItemBlockContent.ts, tests/src/component/copypaste-internal.spec.tsx, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/bulletListItemShortcut-json-chromium-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/bulletListItemShortcut-json-firefox-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/bulletListItemShortcut-json-webkit-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/checkedListItemShortcut-json-chromium-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/checkedListItemShortcut-json-firefox-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/checkedListItemShortcut-json-webkit-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading1Shortcut-json-chromium-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading1Shortcut-json-firefox-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading1Shortcut-json-webkit-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading2Shortcut-json-chromium-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading2Shortcut-json-firefox-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading2Shortcut-json-webkit-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading3Shortcut-json-chromium-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading3Shortcut-json-firefox-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/heading3Shortcut-json-webkit-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/numberedListItemShortcut-json-chromium-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/numberedListItemShortcut-json-firefox-linux.json, tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts-snapshots/numberedListItemShortcut-json-webkit-linux.json, tests/src/utils/copypaste.ts
There was a regression in #1137 which broke keyboard shortcuts for bullet and check list items, which this PR addresses
=> fix: List item shortcuts throwing errors

packages/core/src/api/blockManipulation/commands/removeBlocks/__snapshots__/removeBlocks.test.ts.snap, packages/core/src/api/blockManipulation/commands/removeBlocks/removeBlocks.test.ts, packages/core/src/api/blockManipulation/commands/removeBlocks/removeBlocks.ts, packages/core/src/api/blockManipulation/commands/replaceBlocks/replaceBlocks.ts, packages/xl-multi-column/src/extensions/ColumnResize/ColumnResizeExtension.ts, packages/xl-multi-column/src/extensions/DropCursor/MultiColumnDropCursorPlugin.ts, packages/xl-multi-column/src/test/commands/__snapshots__/removeBlocks.test.ts.snap, packages/xl-multi-column/src/test/commands/__snapshots__/replaceBlocks.test.ts.snap, packages/xl-multi-column/src/test/commands/removeBlocks.test.ts, packages/xl-multi-column/src/test/commands/replaceBlocks.test.ts
This PR fixes 4 bugs to do with multi-column blocks:
1. Dragging a block from one column to another in the same column list now works properly. Previously, it would copy the dragged block instead of moving it.
2. Fixed bug where creating a new column list above an existing one would merge them. This was due to incorrect positions being used in `removeBlocksWithCallback`.
3. Fixed bug where dropping a block inside a new column in a column list would sometimes throw an error, as `nodeDOM` would return `null` due to the cursor position being outdated. I've managed to reproduce this consistently using the document setup below, and dragging the `"bbbbb"` block between the `"c"` and `"d"` blocks.
4. Fixed error being thrown after live reload due to event listeners not getting cleaned up in the …
=> fix: Various multi-column bugs

packages/react/src/components/FilePanel/FilePanelController.tsx, packages/react/src/components/FormattingToolbar/FormattingToolbarController.tsx, packages/react/src/components/LinkToolbar/LinkToolbarController.tsx, packages/react/src/components/SideMenu/SideMenuController.tsx, packages/react/src/components/SuggestionMenu/GridSuggestionMenu/GridSuggestionMenuController.tsx, packages/react/src/components/SuggestionMenu/SuggestionMenuController.tsx
This will allow consumers to pass options to floating-ui.
For example, fixes https://github.com/TypeCellOS/BlockNote/issues/1255 so that `strategy: "fixed"` can be selected
=> feature: expose floatingOptions on react elements

packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts, packages/core/src/extensions/KeyboardShortcuts/KeyboardShortcutsExtension.ts, packages/core/src/extensions/LinkToolbar/LinkToolbarPlugin.ts
This PR addresses the UX issue of using the Tab key to both indent blocks and to navigate UI elements. There are 2 things implemented here:
First, an editor option (`tabKeyboardNavigation`) has been added to disable Tab navigation for the formatting and link toolbars, as well as the file panel. Currently, these elements prevent indenting a selection of blocks while they're open and first require closing using Escape. Setting `tabKeyboardNavigation` to `false` will make Tab and Shift+Tab always indent/unindent blocks, regardless if those elements are shown.
Second, the formatting and link toolbars now stay closed after indenting/unindenting, instead of re-opening each time. The file panel doesn't need changes in this regard.
Closes #1142
=> fix: Tab handling (indentation and toolbar focus)

examples/03-ui-components/07-suggestion-menus-slash-menu-component/styles.css, examples/03-ui-components/09-suggestion-menus-emoji-picker-component/styles.css, packages/ariakit/src/style.css, packages/shadcn/src/style.css
Prevents the page from stretching when suggestion menus are opened
=> fix: update max-height to inherit for suggestion menus

examples/03-ui-components/07-suggestion-menus-slash-menu-component/App.tsx, examples/03-ui-components/09-suggestion-menus-emoji-picker-component/App.tsx
Examples for custom slash commands & emoji picker had the following:
`slash-menu-item${...`
`emoji-picker-item${...`
Due to there being no space, the classNames were being called `slash-menu-itemselected` and `emoji-picker-itemselected` rather than `slash-menu-item selected` and `emoji-picker-item selected`.
=> Typo fixing in examples

packages/core/src/extensions/Placeholder/PlaceholderPlugin.ts
The placeholder extension inserts CSS rules which use pseudo-selectors, specifically `:has`, `:only-child`, and `:before`. These are not supported in older browsers, for example the `:has` selector only works in versions of Firefox after 120.
This PR mitigates the issue by wrapping insertion of the CSS rules in a try/catch block, so that if the CSS selectors aren't supported, the placeholders won't be visible but the error thrown won't break other things in the editor.
Closes #1286
=> fix: Placeholder error handling for inserting CSS rules

docs/README.md, docs/pages/docs/advanced/real-time-collaboration.mdx, examples/07-collaboration/01-partykit/README.md, examples/07-collaboration/02-liveblocks/README.md, examples/07-collaboration/03-y-sweet/.bnexample.json, examples/07-collaboration/03-y-sweet/App.tsx, examples/07-collaboration/03-y-sweet/README.md, examples/07-collaboration/03-y-sweet/index.html, examples/07-collaboration/03-y-sweet/main.tsx, examples/07-collaboration/03-y-sweet/package.json, examples/07-collaboration/03-y-sweet/tsconfig.json, examples/07-collaboration/03-y-sweet/vite.config.ts, package-lock.json, playground/package.json, playground/src/examples.gen.tsx
This PR adds [Y-Sweet](https://jamsocket.com/y-sweet) to…
- …the [Real-time Collaborative rich text editor](https://www.blocknotejs.org/docs/advanced/real-time-collaboration) page in the docs.
- …the Collaboration section of the examples. Note that because Y-Sweet requires a server-side endpoint, we omitted the example embedded within the docs and linked to our example hosted on [demos.y-sweet.dev](https://demos.y-sweet.dev/blocknote?doc=ihvp6vi0u0j).
Also fixes a typo on the Liveblocks and PartyKit examples 🙂 
Also also heads up that I'm getting a bunch of `docs: Module not found: Can't resolve '@blocknote/core'` errors whenever I try to run `npm run build:site`!
=> docs: Add Y-Sweet

packages/core/src/api/clipboard/toClipboard/copyExtension.ts
=> fix: Cut deleting selection when editor is non-editable

packages/core/src/api/blockManipulation/selections/selection.ts, packages/react/src/components/FormattingToolbar/DefaultButtons/CreateLinkButton.tsx
This PR reverts when `getSelection` returns `undefined` to be the same as in 0.19.2, as we unintentionally changed this slightly in 0.20.0.
It also fixes a build issue currently on main that happened due to previous PRs passing CI individually but conflicting when merged.
=> fix: `getSelection` behaviour and build

packages/ariakit/src/index.tsx, packages/mantine/src/index.tsx, packages/react/src/editor/BlockNoteView.tsx, packages/shadcn/src/index.tsx
I think this should resolve the issues here: https://github.com/TypeCellOS/BlockNote/issues/1211#issuecomment-2534944376
(haven't been able to reproduce, but at least this is simpler / shouldn't confuse the typescript compiler if that's the case)
=> fix: BlockNoteView typescript issue for some users

packages/core/src/api/clipboard/__snapshots__/tableAllCells.html, packages/core/src/api/clipboard/__snapshots__/tableCell.html, packages/core/src/api/clipboard/__snapshots__/tableRow.html, packages/core/src/api/clipboard/toClipboard/copyExtension.ts
This PR fixes copy/pasting of tables into spreadsheet applications (like Excel/Google Sheets); #1298
=> fix: Table copy paste into spreadsheets (#1298)

packages/ariakit/tsconfig.json, packages/core/tsconfig.json, packages/mantine/tsconfig.json, packages/react/tsconfig.json, packages/server-util/tsconfig.json, packages/shadcn/tsconfig.json, packages/xl-docx-exporter/tsconfig.json, packages/xl-multi-column/tsconfig.json, packages/xl-pdf-exporter/tsconfig.json, shared/tsconfig.json
Removes an unnecessary `dist/src` directory that was accidentally added on build when enabling tsc project references
=> chore: remove unnecessary files from dist

packages/core/src/editor/editor.css
Because the table handles show up when hovering a table, they slightly cover the content for cells in the leftmost column. This means that the user can't click to select the starts of these cells as they end up clicking the table handle instead.
This PR slightly increases table cell padding so the table handles no longer overlap their content.
=> fix: Selecting start of table cell

packages/core/src/api/parsers/html/__snapshots__/parse-codeblocks.json, packages/core/src/api/parsers/html/parseHTML.test.ts, packages/core/src/blocks/CodeBlockContent/CodeBlockContent.ts
- Fixes code block language parsing (#1344);
- Adds unit tests for verifying expected code block language parsing behavior;
=> fix: Code block language parsing

packages/server-util/vite.config.ts, packages/xl-docx-exporter/package.json, packages/xl-docx-exporter/vite.config.ts, packages/xl-multi-column/package.json, packages/xl-multi-column/vite.config.ts, packages/xl-pdf-exporter/vite.config.ts
Currently, some BlockNote packages include code from React in their built files. Apart from being unnecessary, the code can cause a version mismatch of React, leading to issues. This PR fixes the rollup config so that no React code is included in built files.
Closes #1347
=> fix: Rollup config for `xl` and `server-util` packages

packages/react/src/components/SuggestionMenu/hooks/useSuggestionMenuKeyboardNavigation.ts
I am adding a feature to my Blocknote instance where a modal with a form opens when a suggestion menu item is clicked. The modal behaves as expected when opened via a mouse click on the suggestion menu item. However, when the modal is opened using keyboard navigation, the form auto-submits unexpectedly. I resolved this issue by adding event.stopPropagation.
=> feat: stop suggestion menu event propagation

packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/editor/editor.css
This PR improves the collaboration cursor UX so that the name tag no longer annoyingly blocks user text selection. The UX changes are summarized here: https://github.com/TypeCellOS/BlockNote/issues/1163#issuecomment-2504180222.
> User 1 and 2 collaborate in real-time, from user 1's perspective:
> - When user 2 writes, their name is displayed
> - After X seconds of user 2's inactivity, their name disappears
> - When user 1 hovers over user 2's cursor, user 2's name is displayed for X seconds
> - The cursor remains visible at all times. To improve its visibility, we can either add a dot as suggested by Virgile, or increase its thickness.
Closes #1163
=> feat: Improved collaboration cursor UX

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
This PR fixes the side menu not scrolling with the editor, if the editor is within a scrollable container (works when scrolling document body).
The PR just adds a scroll listener, which is present on all the other UI element plugins.
I spent quite some time playing around with Floating UI to try and get things working without a scroll listener, e.g. by setting [`contextElement`](https://floating-ui.com/docs/virtual-elements#contextelement) as well as `getBoundingClientRect` in `setReference`/`setPositionReference`. I also tried using [`autoUpdate`](https://floating-ui.com/docs/autoupdate), but again had no luck.
I think in general it might be better to keep the scroll listeners though, since it's at least clear in the codebase how those position updates are happening, whereas letting …
=> fix: Side menu scrolling

packages/core/src/i18n/locales/fr.ts
The tooltip for nest and unested was unaccurate opted for the libreoffice version.
=> fix: translation fix in fr.ts

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
The changes introduced in #1341 had some bugs which this PR fixes. The changes are thoroughly documented in the code, but broadly speaking there are 2 main issues that are fixed:
1. `view.dragging` not being cleared & set properly on editors where blocks were not dropped.
2. Overly simplistic handling selection handling on drop.
=> fix: Drag and drop event handling

packages/shadcn/src/components/ui/button.tsx
Set the ShadCN Button component’s type to "button" to prevent unintended form submissions when the editor is used inside a form.
=> fix: shadcn button type

packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/Collaboration/createCollaborationExtensions.ts
fixes:
- Heard from a user they sometimes pass `provider: undefined` in which case we'd throw an error (fixed with `provider?.awareness`)
- "I would like to use showCursorLabels: 'activity', but it is not compatible with renderCursor"
TODO:
=> fix: improve collab cursor code

packages/core/src/editor/editor.css, packages/core/src/extensions/Collaboration/createCollaborationExtensions.ts
This resolves an issue where in Firefox the cursor's caret was breaking to a new line in specific scenarios. Resolves (#1419)
Original issue:
https://github.com/user-attachments/assets/680a8469-284e-4f1a-acde-863638a45f59
After fix is applied:
https://github.com/user-attachments/assets/04d4aa04-2c09-4fa7-95cf-79eb6cb61d99
You'll also notice I repositioned the label to actually line-up to the caret element. I felt like it just looked wrong otherwise. 
Before:
After:
If this should be changed in another PR, then happy to do so, just wanted this to look great. Also willing to make the cursor thicker than 1 px it is right now
=> fix: cursors will not break to new-line on firefox #1419

packages/core/src/editor/editor.css, packages/core/src/extensions/Collaboration/createCollaborationExtensions.ts
Partially reverts commit "e011cf4863e06b6eb07985f379f7750d76b091ee"
This addresses a bug introduced by https://github.com/TypeCellOS/BlockNote/pull/1422 which caused a regression where chrome in some instances would break text wrapping because of the pseudo element's presence in the document.
The pseduo element is now removed, moving back to the original border color approach with an additional fix specifically applied to firefox that will cause the element not to wrap when whitespace is following text
=> fix: chrome should not wrap mid-line

packages/core/src/editor/editor.css, packages/core/src/extensions/Collaboration/createCollaborationExtensions.ts
This fixes a bug with the cursors that will handle zooming and not break to the next line, while still working for firefox & safari
=> fix: chrome zoom bug

package-lock.json, packages/core/package.json, packages/core/src/api/clipboard/toClipboard/copyExtension.ts, packages/core/src/blocks/TableBlockContent/TableBlockContent.ts, packages/core/src/extensions/SideMenu/dragging.ts, packages/react/src/schema/ReactBlockSpec.tsx, packages/xl-multi-column/package.json
closes https://github.com/TypeCellOS/BlockNote/issues/1428
=> fix: upgrade prosemirror view and use correct clipboard import

packages/core/src/api/clipboard/toClipboard/copyExtension.ts
This PR does 2 things:
When the selection is empty, we no longer use our own cut/copy handling and instead let the browser handle the event (so nothing happens). Currently an error is thrown as we attempt to create clipboard data from an empty selection.
When the selection is within a descendant of a `"contenteditable"="false"` element, we no longer use our own cut/copy handling and instead let the browser handle the event. This means the user is selecting some content in a non-editable block. Currently the editor selection is copied instead as this scenario still triggers PM event handlers.
~TODO: Unit tests?~
=> fix: Cut/copy handling in non-editable blocks and empty selections

packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteTipTapEditor.ts, packages/react/src/editor/BlockNoteView.tsx, packages/react/src/editor/EditorContent.tsx
This refactors the old mounting system for React. The biggest improvement is that we don't need `queueMicrotask` in several areas anymore which was a bit of a code smell and possible source for race conditions.
Also cleans up an outdated workaround re onDrop / onPaste that shouldn't be necessary with recent TipTap versions anymore
=> refactor: new react mounting system

packages/core/src/api/blockManipulation/commands/insertBlocks/__snapshots__/insertBlocks.test.ts.snap, packages/core/src/api/blockManipulation/commands/insertBlocks/insertBlocks.test.ts, packages/core/src/api/nodeConversions/blockToNode.ts
This addresses a regression after multi-column where `insertBlocks` (and `blockToNode`) would throw an error if no block type was provided in the partialblock. Also added unit test
closes #1408
=> fix: insertblocks when no type is provided

docs/pages/docs/editor-basics/setup.mdx, examples/01-basic/11-custom-placeholder/App.tsx, examples/01-basic/11-custom-placeholder/README.md, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/Placeholder/PlaceholderPlugin.ts, packages/core/src/i18n/locales/en.ts
Placeholder improvements:
- correctly scope placeholders per editor
- add support for an "empty document" placeholder
Example: https://blocknote-git-fix-improve-placeholders-typecell.vercel.app/basic/custom-placeholder
I'm not sure the current API is great (the way they're passed in via the dictionary), but I think we can address this separately
closes https://github.com/TypeCellOS/BlockNote/issues/703
closes https://github.com/TypeCellOS/BlockNote/issues/1200
=> fix: placeholder improvements

packages/core/src/api/nodeConversions/nodeToBlock.ts, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/i18n/locales/ar.ts, packages/core/src/i18n/locales/de.ts, packages/core/src/i18n/locales/en.ts, packages/core/src/i18n/locales/es.ts, packages/core/src/i18n/locales/fr.ts, packages/core/src/i18n/locales/hr.ts, packages/core/src/i18n/locales/is.ts, packages/core/src/i18n/locales/it.ts, packages/core/src/i18n/locales/ja.ts, packages/core/src/i18n/locales/ko.ts, packages/core/src/i18n/locales/nl.ts, packages/core/src/i18n/locales/pl.ts, packages/core/src/i18n/locales/pt.ts, packages/core/src/i18n/locales/ru.ts, packages/core/src/i18n/locales/uk.ts, packages/core/src/i18n/locales/vi.ts, packages/core/src/i18n/locales/zh.ts, packages/react/src/components/FormattingToolbar/DefaultButtons/AddTiptapCommentButton.tsx, packages/react/src/components/FormattingToolbar/FormattingToolbar.tsx
This PR:
- adds an "add comment" button to the Formatting Toolbar if a commenting plugin has been registered on TipTap
- adds a support to tag certain Marks that are not relevant for BlockNote, such as Marks. TipTap / Liveblocks comment plugins currently rely on marks to associate Comments as annotations to the document, even though they're not really document content. By tagging Marks as `blocknoteIgnore` it's possible to use these marks while not affecting the rest of BlockNote. In Tiptap, this can be done like this:
```typescript
Mark.create(
...
extendMarkSchema(extension) {
if (extension.name === "comment") { // "comment" is the name of the mark
return {
blocknoteIgnore: true,
};
}
return {};
}
...
```
=> feat: add support for tiptap / liveblocks comments

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
This PR fixes an issue with block drag & drop that was introduced in PR #1413. The code block
```ts
if (this.isDragOrigin && !this.pmView.dom.contains(event.target as Node)) {
setTimeout(() => this.pmView.dispatch(this.pmView.state.tr.deleteSelection()), 0);
}
```
is supposed to check if the dragged blocks come from the same editor instance as the handler, but are being dropped in a different editor instance. This is wrong as `!this.pmView.dom.contains(event.target as Node)` can be any element outside the current editor instance, and not necessarily another editor.
And so, all that ends up happening when a drop event occurs outside the current editor instance is that the selection is deleted.
Closes #1396
Closes #1435
=> fix: Blocks being deleted when dropped outside editor container

packages/core/src/util/browser.ts, packages/react/src/editor/BlockNoteContext.ts, packages/react/src/editor/BlockNoteView.tsx, packages/react/src/editor/BlockNoteViewContext.ts
This PR cleans up the BlockNoteView code a bit and adds support for `renderEditor={false}`
The idea is that the consumer can then "position" (render) the editor themselves, but still access the Context values that BlockNoteView is setting up. 
Example usage on a different branch: https://github.com/TypeCellOS/BlockNote/blob/42cdbd1a3c5c580465bb9430a9b81eaaa065aa2f/examples/07-collaboration/04-comments/App.tsx#L150
=> refactor: add renderEditor boolean to BlockNoteView

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts
=> fix: Formatting toolbar `mouseup` handler

packages/core/src/api/clipboard/fromClipboard/handleFileInsertion.ts
=> feat: File insertion QoL

packages/mantine/src/BlockNoteView.tsx
Mantine theme CSS variables aren't being set properly at the moment, which means that an editor using the Mantine `BlockNoteView` may not have the CSS variables it needs when not within an existing `MantineProvider`. This is because `getRootElement` returns no element, but we need it to set `data-mantine-color-scheme` on the `.bn-mantine` element. Since it's a child of the `MantineProvider` and can't be found on render, we have to set `data-mantine-color-scheme` manually through `BlockNoteViewRaw`.
We pretty much never use Mantine theme variables as we use the BlockNote theme variables instead, but the `Badge` components from the comments PR does use them. Maybe we also want to change this to use strictly BlockNote theme variables? (ofc in the comments PR, not this one)
=> fix: Mantine CSS variables element

examples/03-ui-components/15-advanced-tables/.bnexample.json, examples/03-ui-components/15-advanced-tables/App.tsx, examples/03-ui-components/15-advanced-tables/README.md, examples/03-ui-components/15-advanced-tables/index.html, examples/03-ui-components/15-advanced-tables/main.tsx, examples/03-ui-components/15-advanced-tables/package.json, examples/03-ui-components/15-advanced-tables/tsconfig.json, examples/03-ui-components/15-advanced-tables/vite.config.ts, packages/core/src/editor/BlockNoteEditor.ts, packages/react/src/components/FormattingToolbar/DefaultButtons/TableCellMergeButton.tsx, packages/react/src/components/SideMenu/DragHandleMenu/DefaultItems/TableHeadersItem.tsx, packages/react/src/components/TableHandles/TableCellButton.tsx, packages/react/src/components/TableHandles/TableCellMenu/DefaultButtons/ColorPicker.tsx, packages/react/src/components/TableHandles/TableCellMenu/DefaultButtons/SplitButton.tsx, packages/react/src/components/TableHandles/TableHandleMenu/DefaultButtons/ColorPicker.tsx, packages/react/src/components/TableHandles/TableHandleMenu/DefaultButtons/TableHeaderButton.tsx, playground/src/examples.gen.tsx
This adds a new option to the editor instance `settings` which is for editor specific configuration that we want our UI to be reactive to.
For now, it only implements enabling and disabling specific table functionality that may be too much for certain applications. Now, you can use this settings to enable the ability to use those features
=> feat(tables): add the ability to enable/disable table features

packages/react/src/editor/BlockNoteView.tsx
There was a console error being logged because we were passing a ref without using forward ref
=> fix: forward refs to the final component

packages/core/src/extensions/LinkToolbar/LinkToolbarPlugin.ts
This PR fixes an bug with the link toolbar, where `mouseHoveredLinkMark` may be defined even when the mouse cursor isn't hovering any links. This is because the plugin would check if a link is currently hovered by the keyboard or mouse on every state update. State updates may cause the link under the mouse cursor move or be removed outright (such as moving blocks up & down, where it's briefly removed when replacing blocks). However, as no `mouseover` event is fired, `mouseHoveredLinkMark` doesn't get cleared and so an error is thrown if the link doesn't exist.
Therefore, this PR changes the behaviour so that only `keyboardHoveredLinkMark` is considered when updating the link toolbar, unless the update was explicitly called by the `mouseover` handler.
Closes #1479
=> fix: Link toolbar update error

docs/pages/docs/collaboration/comments.mdx
The link to the `DefaultThreadStoreAuth` source code at https://www.blocknotejs.org/docs/collaboration/comments#threadstoreauth is broken; this PR updates the URL.
=> docs: fix link to `DefaultThreadStoreAuth` source code

packages/core/src/editor/editor.css
To help in our liveblocks integration, we are scoping the styles of our cursors to be more specific (based on the `.collaboration-cursor__base` classname) so that we do not conflict with the styles they have setup to style the default tiptap cursors
So, for their CSS to work properly, they will need to provide their own cursor rendering logic to match the default Tiptap one
=> fix: scope cursor caret CSS to be more specific

packages/xl-docx-exporter/src/docx/docxExporter.ts
This resolves a bug in CJS module resolution where the buffer package was incorrectly accessing a named export instead of the default export which is available both in ESM & CJS builds
=> fix: pull from the default export which is available in both ESM and CJS (#1468)

packages/core/src/extensions/SuggestionMenu/getDefaultEmojiPickerItems.ts, packages/react/src/components/Comments/EmojiMartPicker.tsx
This resolves the emoji-mart import dynamically just like what was done in #950 to resolve the same issue.
=> fix: import emoji-mart dynamically like (#950)

packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts
resolves: https://blocknote-js.sentry.io/issues/32147104
=> fix: resolve unneeded error being thrown

packages/core/src/comments/threadstore/ThreadStore.ts, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/extensions/Comments/CommentMark.ts, packages/core/src/extensions/Comments/CommentsPlugin.ts
- removes dependency + check for collaboration, so theoretically you should be able to use comments without yjs
- removes `blocknoteIgnore` (wasn't used, we directly use a property on the mark spec)
=> fix: small issues related to comments

packages/core/src/extensions/SideMenu/dragging.ts
Pretty self explanatory, only seems to be an issue for Chrome but disabled for all browsers since iframes don't correctly show in the drag preview anyway.
=> fix: Drag & drop for blocks with iframes not working

packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts
fixes `Table block does not contain a 'tbody' HTML element. This should never happen.` when in collab mode.
It's a quick fix to fix just this issue. The TableHandlesPlugin definitely needs a refactor to:
a) make the code clearer
b) work better with collaboration. e.g.: we currently also store a nodepos in the state which is unsafe for collaboration scenarios (because the position can change when there are incoming changes)
I'll create a separate ticket for this
=> fix: table error in collaboration mode

packages/core/src/api/nodeConversions/nodeToBlock.ts, packages/core/src/extensions/SuggestionMenu/getDefaultSlashMenuItems.ts, packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts, packages/core/src/schema/inlineContent/types.ts
This is just a series of bug fixes for Sentry errors we are seeing
=> fix: resolve several sentry errors

packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteTipTapEditor.ts, packages/react/src/schema/ReactStyleSpec.tsx
closes https://github.com/TypeCellOS/BlockNote/issues/1535#issuecomment-2731865947
(error was triggered by React 19 which in strictmode also triggers `useMemo` twice)
=> fix: improve markview setup

packages/core/src/api/parsers/html/__snapshots__/parse-2-tables.json, packages/core/src/api/parsers/html/parseHTML.test.ts
adds a unit test for one of the errors fixed in https://github.com/TypeCellOS/BlockNote/pull/1524#discussion_r1998862444
=> chore: add unit test for table parsing

packages/core/src/editor/BlockNoteTipTapEditor.ts
closes https://github.com/TypeCellOS/BlockNote/issues/1513
This only happened for custom react inline content, and not for custom blocks.
The issue was that the creation of the EditorView triggered a prosemirror render calling `renderHTML` on these elements because the nodeviews hadn't been registered yet. For react inline content / react styles, this is implemented by calling `renderToDOMSpec` which triggers a `flushSync`. With this fix, the call to `renderHTML` is avoided as the NodeView will be triggered instead.
A different way to fix this would actually to not use `renderToDOMSpec`  in `renderHTML`, but make it more similar to how we do it for custom blocks. This goes deep into the internals, but would require implementing `toInternalHTML` and `toExternalHTML` for inline content / …
=> fix: immediately add nodeviews to fix flushSync error

packages/core/src/extensions/KeyboardShortcuts/KeyboardShortcutsExtension.ts
This suggestion is for resolving some weird behaviour with the backspace like: Fixes #605 Fixes #1478 .
Also, when a block is empty and backspace is clicked, it makes more sense to remove the block as seen in here:
Old behaviour:
https://github.com/user-attachments/assets/85669900-267a-4f1f-8642-57585d2a77dd
New behaviour:
https://github.com/user-attachments/assets/9f7a8eff-83e0-4e06-af58-cdc275c162d6
=> fix: Backspace in empty block deletes previous block

docs/components/pages/landing/hero/DemoEditor.tsx, examples/01-basic/03-multi-column/App.tsx, examples/01-basic/10-localization/App.tsx, examples/01-basic/11-custom-placeholder/App.tsx, packages/core/package.json, packages/core/src/i18n/index.ts, packages/core/src/index.ts, packages/core/vite.config.ts
Is a breaking change, since I had to change the export, but an easy one to make
Before:
```txt
vite v5.3.4 building for production...
✓ 168 modules transformed.
dist/webpack-stats.json   14.00 kB │ gzip:  2.39 kB
dist/style.css            11.63 kB │ gzip:  2.82 kB
dist/comments.js          17.39 kB │ gzip:  3.51 kB │ map:    49.43 kB
dist/blocknote.js        416.35 kB │ gzip: 93.27 kB │ map: 1,103.85 kB
dist/webpack-stats.json   14.01 kB │ gzip:  2.41 kB
dist/style.css            11.63 kB │ gzip:  2.82 kB
dist/comments.cjs         11.72 kB │ gzip:  2.85 kB │ map:    47.30 kB
dist/blocknote.cjs       273.46 kB │ gzip: 72.57 kB │ map: 1,044.26 kB
✓ built in 506ms
```
After:
```txt
vite v5.3.4 building for production...
✓ 170 modules transformed.
dist/webpack-stats.json   14.50 kB │ gzip: …
```
=> feat: split out localization files for optimized bundle

package-lock.json, packages/core/package.json, packages/core/src/blocks/TableBlockContent/TableExtension.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/HardBreak/HardBreak.ts, packages/core/src/extensions/KeyboardShortcuts/KeyboardShortcutsExtension.ts, packages/core/src/schema/blocks/types.ts
closes https://github.com/TypeCellOS/BlockNote/pull/1554
=> fix: Hard break keyboard shortcut not working in custom blocks

examples/07-collaboration/04-comments/style.css, package-lock.json, packages/core/package.json, packages/core/src/extensions/Comments/CommentsPlugin.ts, packages/server-util/package.json
This PR updates y-prosemirror to v1.3.0, which adds support for overlapping marks. While updating the package does fix the issue, it seems to be pretty much incompatible with clients running the older version. Clients running the new version can still view, resolve, react to, reply to, and delete existing comments, but trying to create a new thread doesn't work properly.
The mark is created correctly and the thread + comment are added to the thread store, but the block containing the mark are deleted immediately after. I spent some time looking into this but could not figure out where this deletion is happening.
Documents which only have clients on the new version work fine.
=> fix: Overlapping marks in comments

packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/extensions/SuggestionMenu/SuggestionPlugin.ts, packages/react/src/components/Comments/ThreadsSidebar.tsx
- **fix: check if relatedTarget exists first**
Resolves: https://blocknote-js.sentry.io/issues/32235378/
- **fix: early exit if html ends up being empty**
Resolves: https://blocknote-js.sentry.io/issues/32467184
- **fix: only set state if it exists**
Resolves: https://blocknote-js.sentry.io/issues/33990038/?environment=vercel-production&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=23
=> fix: some more sentry fixes

docs/pages/docs/editor-basics/default-schema.mdx
This fixes the documentation, update `Default Schema > Default Styles > type Style`'s key `strikethrough` to `strike`.
[Docs for Default Styles](https://www.blocknotejs.org/docs/editor-basics/default-schema#default-styles) shows:
```typescript
type Styles = {
bold: boolean;
italic: boolean;
underline: boolean;
strikethrough: boolean; // this sholud be `strike`
textColor: string;
backgroundColor: string;
};
```
Here's the partial JSON from a request body on `v0.14.0`. I have checked the current `main` branch as of today, and found the value `strike` is the same.
```json
{
"note": [
{
// ... id, type, and props
"content": [
{
"type": "text",
"text": "main text ",
"styles": {}
},
{
"type": "link",
"href": "https://google.com",
"content": [
{
"type": "text",
"text": "link text",
"styles": { …
```
=> fix(docs): update key `strikethrough` to `strike` for the default `Styles` type

packages/core/src/extensions/SuggestionMenu/SuggestionPlugin.ts
This resolves #1473 by allowing the suggestion plugin to switch from one menu to another if it encounters another trigger character
https://github.com/user-attachments/assets/48765b2c-0cce-46d8-9432-e7490d704a4f
This also resolves another issue I ran into personally.
If you type something that ends with `:` that menu is carried over to the new block, even though it shouldn't here is a video before & after.
Before:
https://github.com/user-attachments/assets/8123f0e1-8107-464a-9597-a5da187948de
After:
https://github.com/user-attachments/assets/276d380c-1a17-4a3c-b877-80715a76a1b5
=> fix: allow opening another suggestion menu if another is triggered #1473

packages/core/package.json, packages/server-util/package.json, pnpm-lock.yaml
This only updates y-prosemirror to the latest patch version which includes this fix for selection handling: https://github.com/yjs/y-prosemirror/pull/181
Which resolves #1462
=> fix: update y-prosemirror to fix #1462

packages/core/src/extensions/SuggestionMenu/SuggestionPlugin.ts
Dispatching in the same transaction that modified content could cause positions to be different because of appendedTransactions (e.g. Unique-id plugin)
So, this changes to only dispatch the menu in a separate transaction so that there will likely not be any other content modifications by a meta only dispatch
=> fix: dispatch suggestion menu as a separate transaction

examples/06-custom-schema/04-pdf-file-block/styles.css, packages/core/src/blocks/FileBlockContent/helpers/render/createResizableFileBlockWrapper.ts, packages/core/src/editor/Block.css, packages/react/src/blocks/FileBlockContent/helpers/render/ResizableFileBlockWrapper.tsx
In #731, we broke some things with block styling & selection handling on click, which we didn't fix 100% correctly. One issue that still remains from these changes is the selection moving to the start of the block instead of the end, when clicking the padded area on the right of the area (see #1588 for more detail). The issue is specific to Chrome only.
The reason for this bug is due to the `:before` pseudo-element on each `.bn-block-content` element. Previously,  the `.bn-block-content` element was `display: block`, and so it's `:before` pseudo-element took on `display: inline`. However, we then changed `.bn-block-content` to be `display: flex`, forcing the `:before` pseudo-element to take on `display: block`. Because it was being displayed as a block, and therefore had the same height …
=> fix: Selection handling when clicking editor padding

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts
This PR fixes a regression from #1285 that made it so we weren't updating the formatting toolbar if the document changed but the selection stayed the same.
Closes #1569. However, the toolbar positioning is still janky because it doesn't account for animations. This is a known issue though.
=> fix: Formatting toolbar regression

packages/core/src/blocks/CodeBlockContent/CodeBlockContent.ts
This resolves a bug where if a language is a language that is not within supportedLanguages, it would throw an error rather than silently letting you continue to use it as a plaintext code block 
Sentry bug: https://blocknote-js.sentry.io/issues/37666656/?environment=vercel-production&project=4508925646078032&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=24
=> fix(code-block): handle unknown languages better

examples/03-ui-components/05-side-menu-drag-handle-items/App.tsx
The example for customizing drag handle menu items creates a new component for the custom drag handle menu inline in the `dragHandleMenu` prop in the `SideMenu` component. Because the component is basically recreated on each re-render, the drag handle menu itself gets unnecessarily re-rendered a lot, and this can lead to some issues. Namely the colors dropdown gets hidden while scrolling in the Mantine UI, while the drag handle menu doesn't open at all in the ShadCN UI.
This PR updates the example so that the drag handle component is now defined externally instead of inline, which fixes the re-rendering issues. Tbh I would consider refactoring all of the examples in this way as this is good practice for React, but there's a small trade-off in simplicity that we would be making. However, …
=> docs: Update custom drag handle menu example

packages/core/src/editor/BlockNoteEditor.ts, packages/react/src/components/FilePanel/DefaultTabs/UploadTab.tsx
Implements change proposed in #1637
- Inside the `UploadTab`, pass the block id as parameter to the `editor.uploadFile` function as expected in the function doc
- I also suggested a small variable renaming inside the uploadFule function of the editor because in the rest of the code and docs, `bloc` referres to an editor bloc which is an object but uploadFile expects a string as an input the blockId
```
/**
* The `uploadFile` method is what the editor uses when files need to be uploaded (for example when selecting an image to upload).
* This method should set when creating the editor as this is application-specific.
*
* `undefined` means the application doesn't support file uploads.
*
* @param file The file that should be uploaded.
* @returns The URL of the uploaded file OR an object …
```
=> Pass blockId to uploadFile in UploadTab

packages/react/src/components/FormattingToolbar/DefaultButtons/CreateLinkButton.tsx
tbh, I'm not entirely sure why this was added in the first place with: https://github.com/TypeCellOS/BlockNote/pull/1304/files
But, the issue with this is that during collaboration, the link menu is closed on every content update made by a collaborator (closing this menu continously making a frustrating link experience).
Could use your insight here @matthewlipski
=> fix: do not close the menu on content/selection change

packages/core/src/extensions/FilePanel/FilePanelPlugin.ts
Similar to https://github.com/TypeCellOS/BlockNote/pull/1644 the file panel menu was closing itself when an update to the selection or document changed. Which can happen on every keystroke during collaboration.
This splits up the logic such that the filePluginState can now implicitly close the file panel menu, if it no longer returns a block (this allows maintianing what menu was open across transactions).
=> fix: keep file panel open during collaboration

packages/core/src/api/clipboard/fromClipboard/pasteExtension.ts
This PR forces pasting plain text from the clipboard inside code blocks, as it cannot be formatted anyway and can otherwise result in unexpected behaviour.
Note: No unit test for this has been added as our you have to explicitly choose the clipboard data format for paste tests, which doesn't support this scenario. I think this is fine as it's an explicit edge case anyway.
Closes #1594
=> fix: Force pasting plain text in code block

packages/core/src/i18n/locales/index.ts, packages/core/src/i18n/locales/zh-TW.ts
Contributing `zh-TW` locale for Tranditional Chinese for the project.
=> feat(i18n): add zh-TW locale files

examples/01-basic/03-multi-column/.bnexample.json, examples/05-interoperability/05-converting-blocks-to-pdf/.bnexample.json, playground/src/examples.gen.tsx
As pointed out here: #1666 the multi-column package not being marked as pro is confusing
=> docs: multi-column as pro package

packages/xl-docx-exporter/src/docx/docxExporter.ts, shared/util/fileUtil.ts
Doesn't show up in tests as this is browser only issue.
I have tested in my project though using `pnpm link` and it seems to be working for me now.
Fixes #1675
=> Fix import for buffer as per usage instructions

packages/core/src/extensions/TableHandles/TableHandlesPlugin.ts, packages/react/src/components/TableHandles/TableHandle.tsx
=> fix: exclude non-table blocks from table handles

examples/09-ai/01-minimal/README.md, examples/09-ai/02-playground/README.md, examples/09-ai/03-ai-menu-items/.bnexample.json, examples/09-ai/03-ai-menu-items/App.tsx, examples/09-ai/03-ai-menu-items/README.md, examples/09-ai/03-ai-menu-items/customAIMenuItems.tsx, examples/09-ai/03-ai-menu-items/index.html, examples/09-ai/03-ai-menu-items/main.tsx, examples/09-ai/03-ai-menu-items/package.json, examples/09-ai/03-ai-menu-items/tsconfig.json, examples/09-ai/03-ai-menu-items/vite-env.d.ts, examples/09-ai/03-ai-menu-items/vite.config.ts, packages/xl-ai/src/components/AIMenu/AIMenu.tsx, packages/xl-ai/src/components/AIMenu/AIMenuController.tsx, packages/xl-ai/src/components/BlockNoteAIUI.tsx, packages/xl-ai/src/index.ts, playground/src/examples.gen.tsx
This PR adds an example for custom AI menu items, and makes a few code changes to provide an API for that.
The READMEs of all AI examples have also been updated.
TODO:
- Docs page
=> docs: Custom AI menu items docs

packages/core/src/schema/inlineContent/createSpec.ts
This resolves a bug introduced by https://github.com/TypeCellOS/BlockNote/pull/1609
=> fix: do not use `editor.dispatch`

packages/core/src/editor/Block.css
This PR re-adds `display: flex` only to blocks without inline content, as this was a regression from #1629.
Closes #1687
=> fix: Alignment for blocks without inline content

tests/src/end-to-end/keyboardhandlers/keyboardhandlers.test.ts
Replaces selection logic in PW test done using mouse simulation to use keyboard simulation instead, making it much more reliable.
=> fix: Playwright flaky keyboard handler test

packages/core/src/extensions/KeyboardShortcuts/KeyboardShortcutsExtension.ts
This changes the behavior of shift+enter to attempt to preserve the current marks across an insertion of a hardbreak (shift+enter).
Fixes #1672
=> fix: preserve marks across a shift+enter #1672

packages/xl-pdf-exporter/src/pdf/defaultSchema/blocks.tsx, packages/xl-pdf-exporter/src/pdf/defaultSchema/inlinecontent.tsx, packages/xl-pdf-exporter/src/pdf/pdfExporter.tsx
This adds React keys to the PDF exporter to suppress error messages during export
=> fix: add keys to pdf exporter

packages/core/src/extensions/Collaboration/CursorPlugin.ts
This implements switching the color dynamically based on the user's `.color` property
=> fix: add switch foreground color based on user color #1785

packages/xl-email-exporter/vite.config.ts
closes https://github.com/TypeCellOS/BlockNote/issues/1803
=> fix: mark react package as external in email exporter

packages/react/src/editor/BlockNoteView.tsx, packages/react/src/hooks/useActiveStyles.ts, packages/react/src/hooks/useSelectedBlocks.ts
Adjusted state structurally to allow for simpler useMemo/useCallback usage.
=> fix: Improve React Re-render Loops

packages/react/src/components/TableHandles/ExtendButton/ExtendButton.tsx
=> fix: hide table extend buttons when not editable #1848

packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/BlockChange/BlockChangePlugin.ts
This implements a `BlockChangePlugin` which allows filtering transactions through a callback that provides the higher level blocks changed API
Based on: https://github.com/TypeCellOS/BlockNote/issues/1566#issuecomment-2846940037
=> feat(block-change): adds a new API for blocking changes to editor state, by filtering transactions

packages/core/src/api/__snapshots__/blocks-indented-changed.json, packages/core/src/api/__snapshots__/blocks-moved-deeper-into-nesting.json, packages/core/src/api/__snapshots__/blocks-moved-multiple-in-same-transaction.json, packages/core/src/api/__snapshots__/blocks-moved-to-different-parent.json, packages/core/src/api/__snapshots__/blocks-moved-to-root-level.json, packages/core/src/api/__snapshots__/blocks-outdented-changed.json, packages/core/src/api/blockManipulation/commands/nestBlock/nestBlock.ts, packages/core/src/api/nodeUtil.test.ts, packages/core/src/api/nodeUtil.ts
This implements detecting moves (including indents and outdents) as changes when using the `getBlocksChangedByTransaction` utility.
To implement this, it now has to scan the whole document to know where the parents are, so this may potentially incur a slight reduction in perf
=> feat: report `moves`, indents and outdents as changes when using `getChanges` #1757

packages/core/src/api/clipboard/fromClipboard/handleFileInsertion.ts
This closes #1851 by measuring the DOM node & inserting the file before the dropped on block if the cursor was closer to the top than the bottom
=> fix: insert file upload before block if it is closer to the top of the block

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
- **fix: allow dragging between blocks again**
- **fix: always try to collapse the selection, unless text is being dragged**
=> fix: resolve some minor drag & drop regressions

packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
In case anyone is interested, the TODOs I cleared up were indeed no longer needed. We previously placed the side menu in the vertical center of the block content, and so we needed to use the bounding box of the block content.
We then changed this so the side menu is equal to the height of the block's first line. For blocks without inline content, we use either the overall height of the block, or default to the height of the first line of a paragraph block.
In addition, we also positioned the side menu at the vertical top of the block to match Notion's UX, but kept the side menu code the same since nothing broke. However, it made using the block content bounding box instead of the block bounding box redundant, since the top edge of both is the same height.
=> fix: Minor drag & drop changes

packages/react/src/components/SuggestionMenu/SuggestionMenuController.tsx
=> fix: Suggestion menu closing when clicking scroll bar

packages/core/src/editor/editor.css
This PR fixes the table handles being cut off after changes in #1892, and also cleans up the styles a bit.
=> fix: Table padding

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts
=> fix: Formatting toolbar getting wrong bounding box when updating React inline content

packages/react/src/editor/BlockNoteView.tsx
This PR fixes an issue where getting `editor.isEditable` in the `render` function of a vanilla JS block would return `true`, regardless of if the editor is actually editable.
This is because `editor.isEditable` is set in a `useEffect` hook in `BlockNoteViewComponent`, which updates the value async, and so it can happen after the block has already rendered.
I've changed it so `editor.isEditable` is also set in `BlockNoteViewEditor`, before the editor is mounted, ensuring the value is correct before any vanilla blocks are rendered.
Closes #1477
=> fix: Vanilla blocks return `true` for `editor.isEditable` on initial render

examples/01-basic/02-block-objects/src/App.tsx
=> docs: Fix "Displaying Document JSON" example

examples/03-ui-components/02-formatting-toolbar-buttons/README.md, examples/03-ui-components/02-formatting-toolbar-buttons/src/App.tsx, examples/03-ui-components/02-formatting-toolbar-buttons/src/BlueButton.tsx
=> docs: Fix "Adding Formatting Toolbar Buttons" example

docs/content/docs/reference/editor/overview.mdx
Title
Update docs to isEditable from editor.editable
Description
The key editable seems to be a holdover from the docs for the component prop. When setting it on the editor instance it should be editor.isEditable
=> fix: update docs editor.editable to editor.isEditable

packages/xl-docx-exporter/src/docx/__snapshots__/basic/styles.xml, packages/xl-docx-exporter/src/docx/__snapshots__/withMultiColumn/styles.xml, packages/xl-docx-exporter/src/docx/docxExporter.test.ts, packages/xl-docx-exporter/src/docx/docxExporter.ts, shared/util/fileUtil.ts
**Title**
Add configurable locale for DOCX export (default: en-US)
**Description**
This PR introduces the ability to configure the default language of the generated .docx files via a new optional locale parameter in createDefaultDocumentOptions.
issue [1896](https://github.com/TypeCellOS/BlockNote/issues/1896)
**Details**
- Added locale?: string parameter to allow consumers of the library to set the document’s default language in the styles.xml metadata (<w:lang w:val="..."/>).
- If no locale is provided, the default is set to en-US.
- This change improves accessibility: screen readers rely on the document’s language metadata to pronounce words correctly.
- Implementation replaces the existing language in styles.xml while preserving other attributes.
**Example usage**
```
const exporter = …
```
=> add locale configuration for docx export

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts
Select all content manually, or use the shortcut Ctrl+A / Cmd+A.
The editor enters an infinite render loop and eventually crashes the page.
In the `FormattingToolbarView` update event handler, the logic attempts to check the selection boundary to determine whether the formatting toolbar is rendered.
If the toolbar isn’t rendered, it forces the view to update.
When all content is selected, posToDOMRect (from Tiptap) reports a selection width of 0.
This results in the handler continuously scheduling forced updates, creating an infinite render loop.
```
// Why width = 0?
| <- Start (left = 0, right = 0)
Content Content Content Content
| <- End (left = 0, right = 0)
const width = right - left; // width = 0
```
#965 
#1908
=> [CRITICAL] Fix: Infinite render loop when selecting all content (Ctrl+A / Cmd+A)

packages/core/src/extensions/FormattingToolbar/FormattingToolbarPlugin.ts
Continuing from #1956, this PR slightly alters the change so the code matches what the comment says it's supposed to do. This shouldn't really change anything, it's just more semantically correct.
=> fix: Minor change to formatting toolbar extension logic

packages/server-util/vite.config.ts
This properly externalizes react, react-dom, react-dom/client from the server-util bundle, allowing users to use whatever version of React their application requires
=> build: externalize deps from server-util #1966

packages/shadcn/src/index.tsx
There might be cases where some components controlling the editor are outside of `BlockNoteView`. In that case, the context will be missing, and it needs to be exported to gain access to it.
=> feat: export ShadCNComponentsContext

packages/core/src/blocks/TableBlockContent/TableBlockContent.ts, packages/core/src/editor/editor.css, tests/src/end-to-end/tables/tables.test.ts, tests/src/end-to-end/tables/tables.test.ts-snapshots/arrowKeyCells-json-chromium-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/arrowKeyCells-json-firefox-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/arrowKeyCells-json-webkit-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/cellTyping-json-chromium-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/cellTyping-json-firefox-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/cellTyping-json-webkit-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/tabCells-json-chromium-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/tabCells-json-firefox-linux.json, tests/src/end-to-end/tables/tables.test.ts-snapshots/tabCells-json-webkit-linux.json, tests/src/utils/const.ts
=> fix: Typing in empty table cells

docs/content/docs/features/collaboration/comments.mdx, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/BlockNoteExtensions.ts, packages/core/src/extensions/Comments/CommentsPlugin.ts, packages/react/src/components/Comments/Comment.tsx, packages/react/src/components/Comments/CommentEditor.tsx, packages/react/src/components/Comments/FloatingComposer.tsx, packages/react/src/components/Comments/Thread.tsx, packages/react/src/components/Comments/defaultCommentEditorSchema.ts
=> feat: Custom schemas for comment editors

packages/core/src/editor/BlockNoteEditor.ts
=> feat(core): add the ability to autofocus on the editor element

packages/core/src/blocks/ListItem/BulletListItem/block.ts, packages/core/src/blocks/ListItem/NumberedListItem/block.ts
=> fix: disable input rules for numbered headings #1789

docs/content/docs/reference/editor/events.mdx, packages/core/src/editor/BlockNoteEditor.test.ts, packages/core/src/editor/BlockNoteEditor.ts, packages/core/src/editor/managers/EventManager.ts
This change allows for using `editor.onChange` before the `editor.tiptapEditor` is actually assigned. This allows us to not have to wrap every event we register in extensions (the only time you'd have access to the editor instance without the tiptapEditor being initialized), be forced to be wrapped in `editor.onCreate`.
This simplifies extension code to be the same as what you'd use with a fully constructed editor instance.
De-coupled the event handling to be done on the EventManager instance by making it into an EventEmitter
Should be no change
Added tests to prove that this works, also added tests for the new onMount & onUnMount events that I exposed as part of this
=> fix: allow listening to `onChange` and other events before the underlying editor is initialized
