- tests/end-to-end/dragdrop/dragdrop.test.ts
- tests/end-to-end/dragdrop/dragdrop.test.ts-snapshots/dragdropnested-chromium-linux.json
- tests/end-to-end/dragdrop/dragdrop.test.ts-snapshots/dragdropnested-firefox-linux.json
- tests/end-to-end/dragdrop/dragdrop.test.ts-snapshots/dragdropnested-webkit-linux.json
- tests/end-to-end/dragdrop/dragdrop.test.ts-snapshots/dragdropsingle-chromium-linux.json
- tests/end-to-end/dragdrop/dragdrop.test.ts-snapshots/dragdropsingle-firefox-linux.json
- tests/end-to-end/dragdrop/dragdrop.test.ts-snapshots/dragdropsingle-webkit-linux.json
- tests/end-to-end/draghandle/draghandle.test.ts
- tests/utils/debug.ts
- tests/utils/draghandle.ts
- tests/utils/mouse.ts
This PR adds tests for dragging $ dropping blocks.
> Added drag & drop tests

- packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts
This PR fixes the drag handle not updating when the editor changes position or dimensions. It also fixes hovered block updating when the editor changes position.
> Drag handle position fix

- examples/vanilla/src/ui/slashMenuFactory.ts
- packages/core/src/extensions/SlashMenu/SlashMenuExtension.ts
- packages/core/src/extensions/SlashMenu/SlashMenuItem.ts
- packages/core/src/extensions/SlashMenu/defaultCommands.tsx
- packages/core/src/extensions/SlashMenu/index.ts
- packages/core/src/shared/plugins/suggestion/SuggestionItem.ts
- packages/core/src/shared/plugins/suggestion/SuggestionPlugin.ts
- packages/core/src/shared/plugins/suggestion/SuggestionsMenuFactoryTypes.ts
- packages/react/src/FormattingToolbar/components/FormattingToolbar.tsx
- packages/react/src/SlashMenu/components/SlashMenu.tsx
This PR refactors the suggestions plugin to hopefully make it more readable and provide better documentation.
> Suggestion plugin refactor

- packages/core/src/api/nodeConversions/nodeConversions.ts
Addresses this feedback: https://github.com/YousefED/BlockNote/pull/108#discussion_r1126348393
It adds one extra loop + duplicate node instantiation in:
```
const nodes = styledTextArrayToNodes(link.content, schema).map((node) => {
return node.mark([...node.marks, linkMark]);
});
```
However, it's probably a bit cleaner. wdyt @matthewlipski ?
> refactor links a bit

- packages/website/vercel.json
works with following settings:
> add vercel config

- packages/core/src/extensions/Blocks/nodes/BlockContainer.ts
This PR makes `BNDeleteBlock` no longer set the selection and focus. Also removes `BNCreateOrUpdateBlock` as it's no longer needed.
> `BNDeleteBlock` Fix

- README.md
- packages/website/docs/.vitepress/config.ts
- packages/website/docs/.vitepress/theme/components/Home.vue
- packages/website/docs/docs/introduction.md
closes https://github.com/YousefED/BlockNote/issues/119
> fix discord links

- packages/core/src/BlockNoteEditor.ts
This recently regressed. Fixes the issued mentioned here: https://github.com/YousefED/BlockNote/issues/104#issuecomment-1468542961
> fix: options.parentElement did not work

- packages/website/docs/.vitepress/config.ts
> fix github link in nav

- packages/website/docs/docs/blocks.md
- packages/website/docs/docs/converting-blocks.md
- packages/website/docs/docs/cursor-selections.md
- packages/website/docs/docs/quickstart.md
- packages/website/docs/docs/slash-menu.md
This PR cleans up type hints and comments for demos in the documentation.
> Website Demos Cleanup

- examples/editor/package.json
- examples/vanilla/package.json
- lerna.json
- package-lock.json
- packages/core/package.json
- packages/core/src/extensions/DraggableBlocks/DraggableBlocksPlugin.ts
- packages/react/package.json
- packages/website/package.json
This might fix https://github.com/TypeCellOS/BlockNote/issues/123.
Probably caused by two BlockNote instances (might be because of React Strictmode, but as it's difficult to reproduce, let's see if this workaround fixes it)
closes https://github.com/TypeCellOS/BlockNote/issues/123
> Fix nearest desc error

- packages/website/docs/.vitepress/config.ts
> docs: add vercel analytics to website

- examples/editor/package.json
- examples/vanilla/package.json
- lerna.json
- package-lock.json
- packages/core/package.json
- packages/react/package.json
- packages/website/package.json
see https://stackoverflow.com/a/76212193
> chore: fix type imports

- packages/react/src/hooks/useBlockNote.ts
this will make it easier to disable / change a single UI factory
closes https://github.com/TypeCellOS/BlockNote/issues/197
> fix: use nicer defaults for react UIFactories

- packages/react/src/SharedComponents/Toolbar/components/ToolbarDropdownTarget.tsx
fixes https://github.com/TypeCellOS/BlockNote/issues/246
> fix: warning in console about unsupported isselected prop

- packages/website/docs/.vitepress/config.ts
Adds Algolia Docsearch
Closes #157
> docs: add docsearch

- packages/react/src/FormattingToolbar/components/DefaultDropdowns/BlockTypeDropdown.tsx
- packages/website/docs/docs/block-types.md
- packages/website/docs/docs/blocks.md
- packages/website/docs/docs/converting-blocks.md
- packages/website/docs/docs/cursor-selections.md
- packages/website/docs/docs/formatting-toolbar.md
- packages/website/docs/docs/introduction.md
- packages/website/docs/docs/slash-menu.md
- packages/website/docs/docs/ui-elements.md
This update fixes and improves most demos in the documentation. It also fixes a bug in the `BlockTypeDropdown` component with custom blocks, which was also causing issues in one of the demos.
> fix: Updates for demos in docs

- packages/core/src/BlockNoteEditor.ts
> fix: hotfix initialcontent

- packages/react/src/FormattingToolbar/components/DefaultDropdowns/BlockTypeDropdown.tsx
> fix: Block type dropdown not being visible for heading blocks

- packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
> fix: Side menu not appearing after clicking add block button

- packages/core/src/extensions/Blocks/nodes/Block.module.css
> fix: Custom blocks with inline content overflow

- packages/react/src/BlockNoteTheme.ts
- packages/website/docs/docs/block-types.md
- packages/website/docs/docs/image-toolbar.md
- packages/website/docs/docs/slash-menu.md
- packages/website/docs/docs/theming.md
- packages/website/docs/docs/ui-elements.md
- packages/website/docs/examples/alert-block.md
- packages/website/docs/examples/block-manipulation.md
- packages/website/docs/examples/keyboard-shortcuts.md
This PR includes a small update to the docs, namely a fix for the Alert block example and a small fix to theming docs. Closes #377
> docs: Minor fixes

- .github/workflows/build.yml
- .github/workflows/relative-ci.yaml
- examples/editor/package.json
- examples/editor/vite.config.ts
- package-lock.json
- packages/core/package.json
- packages/core/vite.config.ts
- packages/react/package.json
- packages/react/vite.config.ts
> chore: setup relative ci

- examples/editor/package.json
- package-lock.json
- package.json
- packages/core/package.json
- packages/react/package.json
- tests/package.json
> fix: `BlockNoteView` types export

- packages/core/src/editor/BlockNoteEditor.ts
- packages/core/src/editor/editor.css
> fix: NextJS tables CSS error

- packages/core/src/extensions/SideMenu/SideMenuPlugin.ts
> fix: Add block button incorrect cursor position

- packages/core/src/pm-nodes/BlockContainer.ts
> fix: Delete handler error when cursor in last block

- packages/core/src/editor/Block.css
Code styles were missing any kind of styling, so this PR just changes the font to be monospaced for those.
> fix: Code styles

- packages/react/src/editor/styles.css
> Fix: Minor CSS

- packages/website/docs/.vitepress/config.ts
- packages/website/docs/examples/formatting-toolbar-buttons.md
> docs: Formatting toolbar code toggle button example

- packages/core/src/editor/BlockNoteEditor.ts
> fix: collaboration and editable false bug

- examples/06-collaboration/02-liveblocks/App.tsx
- examples/06-collaboration/02-liveblocks/README.md
- examples/06-collaboration/02-liveblocks/index.html
Hey there, nice work on the new docs, they're looking good! Just a quick update, we don't use the upper case "B" in our branding.
> LiveBlocks → Liveblocks

- packages/react/src/schema/ReactInlineContentSpec.tsx
Fixes https://github.com/TypeCellOS/BlockNote/issues/634
@matthewlipski could you also add a Tag (editable ic) example to the examples?
> fix: inline content react remounting

- package-lock.json
- packages/react/package.json
> fix: clean react package deps

- packages/core/src/i18n/locales/fr.ts
- packages/core/src/i18n/locales/index.ts
This Pull Request adds the fr.ts file wich export the french dictionary
> Add french locales to dictionary

- packages/core/src/i18n/locales/index.ts
- packages/core/src/i18n/locales/zh.ts
I think that i18n should be configured by the developers themselves according to the documentation examples, but for those who wish to use it directly, they undoubtedly have one more option.
> feat: Add Chinese i18n support

- packages/core/src/i18n/locales/index.ts
- packages/core/src/i18n/locales/ja.ts
I have included Japanese i18n support. Please review. I would like to utilize it in Japan.
> feat: Add Japanese i18n support

- packages/react/src/editor/BlockNoteView.tsx
> fix: export blocknoteviewprops

- examples/05-custom-schema/04-pdf-file-block/PDF.tsx
- examples/05-custom-schema/04-pdf-file-block/styles.css
> fix: PDF block example styling

- packages/core/src/i18n/locales/pt.ts
Hi,
pr as request on issue #803
> fix pt.ts translation

- packages/react/src/components/SuggestionMenu/SuggestionMenuController.tsx
Maybe related: https://github.com/TypeCellOS/BlockNote/issues/778
My assumption is there is a race condition because the event handler (useUIstate) keeps getting attached / detached. This should improve that, but regardless it's a nice cleanup anyway
> fix: add memoization in suggestion menu

- docs/package.json
- package-lock.json
closes https://github.com/TypeCellOS/BlockNote/issues/821
> chore: upgrade nextjs

- packages/core/src/i18n/locales/index.ts
- packages/core/src/i18n/locales/ru.ts
Russian translation added
Добавлен русский перевод
> Russian translation added

- packages/core/src/editor/BlockNoteExtensions.ts
The `CollaborationCursorOptions` allow `user` to be `Record<string, any>;`, which allows the ability to add any custom fields to the user awareness.
This expands the typing to allow developers to take advantage of this.
> feat: Allow custom user fields

- docs/pages/docs/custom-schemas.mdx
- docs/pages/docs/editor-basics/setup.mdx
- docs/pages/docs/ui-components/side-menu.mdx
- examples/03-ui-components/02-formatting-toolbar-buttons/README.md
> docs: Fix dead links

- packages/core/src/i18n/locales/es.ts
This PR is to add the spanish internationalization and make it available.
> Add feature  - Spanish dictionary.

- packages/mantine/src/style.css
- packages/react/src/components/SuggestionMenu/GridSuggestionMenu/GridSuggestionMenuController.tsx
- packages/react/src/components/SuggestionMenu/SuggestionMenuController.tsx
> fix: slash menu "no items" positioning

- packages/core/src/i18n/locales/de.ts
- packages/core/src/i18n/locales/index.ts
- Added: German language file (de.ts) containing translations.
- Tested: Manually verified the translations by switching the app language to German and checking each screen for correctness and consistency.
> feat: added german translation

- packages/core/src/editor/BlockNoteEditor.ts
- tests/src/end-to-end/textalignment/textAlignment.test.ts
close #1014 
/claim #1014
https://github.com/user-attachments/assets/f6034ba6-d1b2-46ca-884a-39e1b3d2436e
> fix: Unexpected getSelection

- packages/core/src/schema/blocks/createSpec.ts
- packages/react/src/schema/ReactBlockSpec.tsx
> fix: Error when copying custom blocks

- packages/core/vite.config.ts
make sure languages are not output to core/dist
> chore: externalize shiki languages

- packages/core/src/api/blockManipulation/commands/insertBlocks/__snapshots__/insertBlocks.test.ts.snap
- packages/core/src/api/blockManipulation/commands/mergeBlocks/__snapshots__/mergeBlocks.test.ts.snap
- packages/core/src/api/blockManipulation/commands/moveBlock/__snapshots__/moveBlock.test.ts.snap
- packages/core/src/api/blockManipulation/commands/removeBlocks/__snapshots__/removeBlocks.test.ts.snap
- packages/core/src/api/blockManipulation/commands/replaceBlocks/__snapshots__/replaceBlocks.test.ts.snap
- packages/core/src/api/blockManipulation/commands/splitBlock/__snapshots__/splitBlock.test.ts.snap
- packages/core/src/api/blockManipulation/commands/updateBlock/__snapshots__/updateBlock.test.ts.snap
- packages/core/src/api/parsers/html/__snapshots__/parse-notion-html.json
- packages/core/src/blocks/TableBlockContent/TableBlockContent.ts
> fix: Remove background color from table props

- packages/core/src/editor/BlockNoteEditor.ts
- packages/core/src/editor/BlockNoteExtensions.ts
fix for `disableExtensions` + small extra error message
> fix: disableExtensions

- packages/core/src/i18n/locales/ru.ts
Fixed russian translation for file delete tooltip
> fix: delete file ru tooltip

- packages/react/src/schema/ReactBlockSpec.tsx
- packages/react/src/schema/ReactInlineContentSpec.tsx
closes https://github.com/TypeCellOS/BlockNote/issues/1287
closes https://github.com/TypeCellOS/BlockNote/issues/1293
> fix: useReactNodeView ref for React 19 compatibility

- packages/core/src/editor/editor.css
Makes the css rules for the table block more specific. This way custom blocks that have tables inside of them won't be affected by these rules
> feat: add more css specificity for tables

- packages/core/src/i18n/locales/index.ts
- packages/core/src/i18n/locales/it.ts
Just added Italian translations :)  🇮🇹
> Add Italian Translations 🇮🇹

- packages/core/src/editor/BlockNoteEditor.ts
@m-risto would this work for you? you can pass a factory function that gets the editor
> feat: add factory function for extensions

- examples/01-basic/04-default-blocks/App.tsx
Removed scrollable container added in #1394
> docs: Default blocks example fix

- packages/core/src/api/nodeConversions/nodeToBlock.ts
- packages/core/src/blocks/TableBlockContent/TableBlockContent.ts
How crazy would it be to just allow table cells to have multiple table paragraphs to allow them to merge cleanly, then just store that back in the json cleanly?
I made this as a separate PR since the other one is getting rather large & this is more experimental
> fix(table): table cell merging

- packages/react/vite.config.ts
closes https://github.com/TypeCellOS/BlockNote/issues/1358
> fix: externalize react-dom/client

- packages/core/package.json
caused an error with yarn (see discord)
> fix: peerDependenciesMeta typo

- examples/05-interoperability/05-converting-blocks-to-pdf/.bnexample.json
- examples/05-interoperability/05-converting-blocks-to-pdf/App.tsx
- examples/05-interoperability/05-converting-blocks-to-pdf/package.json
- package-lock.json
- packages/xl-pdf-exporter/package.json
- packages/xl-pdf-exporter/src/pdf/util/listItem.tsx
- playground/src/examples.gen.tsx
upgrades react-pdf and fixes compatibility (removes `fontFamily:""`)
> fix: compatibility with new react-pdf

- package-lock.json
- packages/core/package.json
- packages/core/src/extensions/Collaboration/createCollaborationExtensions.ts
- packages/server-util/package.json
fixes "Could not find client state for user" error
can we release a patch 0.23.3 version?
> fix: upgrade y-prosemirror and remove clientID hack

- packages/core/src/editor/editor.css
- packages/core/src/extensions/Collaboration/createCollaborationExtensions.ts
Addresses: https://github.com/TypeCellOS/BlockNote/pull/1492#pullrequestreview-2660967381
> fix: prefix the collaboration cursor classname

- packages/core/src/api/nodeConversions/nodeToBlock.ts
This resolves a bug that could crash the page in specific situations
> fix: check for undefined headerMatrix resolves #1506

- packages/react/src/components/SideMenu/DefaultButtons/DragHandleButton.tsx
This makes it just a bit easier to set the menu items within the draghandle menu
> fix: better expose setting a draghandlemenu's items #1525

- packages/core/src/i18n/locales/ru.ts
> chore: update russian translation

- docs/app/AuthenticationPage.tsx
- docs/app/signin/email/page.tsx
- docs/app/signin/page.tsx
- docs/app/signup/page.tsx
- docs/components/AuthNavButton.tsx
- docs/theme.config.tsx
This PR adds a proper sign-up page, as well as magic link and BlockNote account login pages.
TODO:
> feat: Sign-up/login flows & UI

- docs/pages/docs/ai/getting-started.mdx
> docs: add stylesheet

- docs/auth.ts
- **fix: do not send email on use of a magic link**
- **fix: on subscription.active, check subscription status**
> fix(website): log in bug fixes

- packages/core/src/editor/editor.css
> fix: Overflow on table blocks

- packages/react/src/components/TableHandles/TableCellMenu/TableCellMenu.tsx
> fix: Table cell menu styling

- docs/app/layout.tsx
- docs/app/styles.css
> docs: Made UI elements no longer overflow demo box

- packages/core/src/blocks/Code/block.ts
Closes #2041
This PR does not add tests, as this is a highly specific issue. We should consider adding tests for this functionality later.
> fix: Code block language select value not updating properly

- packages/react/src/components/Comments/Comment.tsx
> fix: Reaction picker shown for users who can't react
